- frontend/src/assets/img/thumbnail-bg.svg
- frontend/src/view/thumbnail/ThumbnailPage.vue
> [Feat] 메인 페이지

- .idea/.gitignore
- backend/.gitignore
- backend/src/main/java/minionz/backend/chat_room/model/ChatRoom.java
- backend/src/main/java/minionz/backend/message/model/Message.java
- backend/src/main/java/minionz/backend/message/model/MessageStatus.java
- backend/src/main/java/minionz/backend/message/model/MessageType.java
- backend/src/main/java/minionz/backend/user/model/User.java
- backend/src/main/resources/application.yml
#2 
<br>
- 채팅 관련 엔티티 관계랑 속성 전부 추가 후에 올렸습니다. 제대로 관계가 맺어지지 않아서 오류가 생긴다고 해서 수정 했습니다!
<br> 
`application.yml` 을 환경 변수로 처리 해 두고 `application-local.yml` 을 따로 만들어서 관리하게 했습니다. gitignore에 local을 추가 해 뒀으니 방법 모르시면 말씀 해 주시면 설정 해 드리겠습니다. 
idea에 있는 gitignore는 변경 한 적이 없는데 변경 되었다고 뜨길래 develop에 있는 것과 비교 했는데 같은 것을 확인 했습니다. 충돌은 생길 것 같지 않아서 재차 올립니다.
> [Feat] 채팅 관련 관계 추가 #2

- backend/src/main/java/minionz/backend/chat/chat_room/model/request/CreateChatRoomRequest.java
- backend/src/main/java/minionz/backend/chat/chat_room/model/response/CreateChatRoomResponse.java
- backend/src/main/java/minionz/backend/chat/message/model/request/MessageRequest.java
- backend/src/main/java/minionz/backend/chat/message/model/response/MessageResponse.java
#2 #20
<br>
- Config 파일 내에서 Request를 받아와서 쓰는 부분이 있어서 다른 분들이 에러가 뜨는 것 같아 미리 올리게 됐습니다. 
- ChatRoom, Message 부분 Response, Request 부분만 넣었고 바뀔 부분은 현재까지 없습니다!
<br> 
없습니다.
> [Feat] 채팅 Request, Response 부분 구현 [#2, #20]

- backend/src/main/java/minionz/backend/common/responses/BaseResponseStatus.java
<br>
- 누락된 BaseResponseStatus 를 추가했습니다.
<br>
> [Refactor] ETC_002 - 누락된 BaseResponseStatus 추가

- backend/src/main/java/minionz/backend/config/SecurityConfig.java
- backend/src/main/java/minionz/backend/scrum/workspace/WorkspaceController.java
- backend/src/main/java/minionz/backend/scrum/workspace/WorkspaceRepository.java
- backend/src/main/java/minionz/backend/scrum/workspace/WorkspaceService.java
- backend/src/main/java/minionz/backend/scrum/workspace/model/response/ReadWorkspaceResponse.java
#75 
<br>
- 워크스페이스 조회 dto를 구현했습니다.
- 편리한 개발 환경을 위하여 임시로 시큐리티 컨피그를 구현했습니다.
<br> 
- 로그인 기능 구현 후 유저를 수정할 예정입니다.
close #75
> [Feat] WORKSPACE_002 - 워크스페이스 조회 기능 구현 [#75]

- backend/src/main/java/minionz/backend/BackendApplication.java
- backend/src/main/java/minionz/backend/common/exception/BaseException.java
- backend/src/main/java/minionz/backend/common/responses/BaseResponseStatus.java
- backend/src/main/java/minionz/backend/config/s3/S3Config.java
- backend/src/main/java/minionz/backend/error_board/ErrorBoardController.java
- backend/src/main/java/minionz/backend/error_board/ErrorBoardImageRepository.java
- backend/src/main/java/minionz/backend/error_board/ErrorBoardRepository.java
- backend/src/main/java/minionz/backend/error_board/ErrorBoardService.java
- backend/src/main/java/minionz/backend/error_board/model/ErrorBoard.java
- backend/src/main/java/minionz/backend/error_board/model/ErrorBoardCategory.java
- backend/src/main/java/minionz/backend/error_board/model/ErrorBoardImage.java
- backend/src/main/java/minionz/backend/error_board/model/request/CreateErrorBoardRequest.java
- backend/src/main/java/minionz/backend/error_board/model/response/CreateErrorBoardResponse.java
- backend/src/main/java/minionz/backend/error_board/model/response/GetErrorBoardImageResponse.java
- backend/src/main/java/minionz/backend/error_comment/ErrorCommentController.java
- backend/src/main/java/minionz/backend/error_comment/ErrorCommentService.java
- backend/src/main/java/minionz/backend/error_comment/ErrorCommnetRepository.java
- backend/src/main/java/minionz/backend/error_comment/model/ErrorCommentImage.java
- backend/src/main/java/minionz/backend/scrum/workspace/model/Workspace.java
- backend/src/main/java/minionz/backend/user/model/User.java
- backend/src/main/java/minionz/backend/utils/CloudFileUpload.java
- backend/src/main/resources/application.yml
#13 
<br>
- 제목 내용 카테고리 이미지 업로드 기능 완료
<br>
> [Feat] ERROR_BOARD_001 - 에러게시글 생성 기능 구현

- .idea/be06-fin-MINIONZ-CalIT.iml
- .idea/compiler.xml
- .idea/gradle.xml
- .idea/inspectionProfiles/Project_Default.xml
- .idea/jarRepositories.xml
- .idea/misc.xml
- .idea/modules.xml
- .idea/vcs.xml
- backend/src/main/java/minionz/backend/common/responses/BaseResponseStatus.java
- backend/src/main/java/minionz/backend/error_board/ErrorBoardController.java
- backend/src/main/java/minionz/backend/error_board/ErrorBoardRepository.java
- backend/src/main/java/minionz/backend/error_board/ErrorBoardService.java
- backend/src/main/java/minionz/backend/error_board/model/ErrorBoard.java
- backend/src/main/java/minionz/backend/error_board/model/ErrorBoardImage.java
- backend/src/main/java/minionz/backend/error_board/model/response/GetErrorBoardResponse.java
- backend/src/main/java/minionz/backend/error_comment/model/ErrorComment.java
- backend/src/main/java/minionz/backend/error_comment/model/ErrorCommentImage.java
#21
<br>
- 에러게시글 전체 조회 기능 구현
- 엔티티 수정
<br>
>  [Feat] ERRORBAORD_002 에러게시글 조회 기능 구현 [#21]

- backend/src/main/java/minionz/backend/common/responses/BaseResponseStatus.java
- backend/src/main/java/minionz/backend/error_board/model/ErrorBoard.java
- backend/src/main/java/minionz/backend/error_comment/model/ErrorComment.java
- backend/src/main/java/minionz/backend/scrum/label/LabelController.java
- backend/src/main/java/minionz/backend/scrum/label/LabelService.java
- backend/src/main/java/minionz/backend/scrum/label/SprintLabelRepository.java
- backend/src/main/java/minionz/backend/scrum/label/TaskLabelRepository.java
- backend/src/main/java/minionz/backend/scrum/label/model/SprintLabel.java
- backend/src/main/java/minionz/backend/scrum/label/model/TaskLabel.java
- backend/src/main/java/minionz/backend/scrum/label/model/request/CreateLabelRequest.java
- backend/src/main/java/minionz/backend/scrum/sprint_label_select/model/SprintLabelSelect.java
- backend/src/main/java/minionz/backend/scrum/task_label_select/model/TaskLabelSelect.java
- backend/src/main/java/minionz/backend/scrum/workspace/model/Workspace.java
- backend/src/main/java/minionz/backend/scrum/workspace_participation/WorkspaceParticipationRepository.java
#78 #82 
<br>
- 스프린트 라벨 생성 기능을 구현했습니다.
- 태스크 라벨 생성 기능을 구현했습니다.
- 라벨 생성 시 발생할 수 있는 예외를 처리했습니다.
- 게시판에서 발생하는 오류 처리를 위해 문법을 수정하고 연관 관계를 삭제했습니다.
<br> 
- 게시판과 스크럼 폴더 하위 테이블 사이의 관계로 인해 오류가 발생하여 우선 제거해뒀습니다. 추후 다시 구현이 필요합니다.
close #78 
close #82
> [Feat] WORKSPACE_005, WORKSPACE_009 - 스프린트 라벨 및 태스크 라벨 생성 기능 구현 [#78, #82]

- backend/src/main/java/minionz/backend/common/responses/BaseResponseStatus.java
- backend/src/main/java/minionz/backend/scrum/label/LabelController.java
- backend/src/main/java/minionz/backend/scrum/label/LabelService.java
- backend/src/main/java/minionz/backend/scrum/label/SprintLabelRepository.java
- backend/src/main/java/minionz/backend/scrum/label/TaskLabelRepository.java
- backend/src/main/java/minionz/backend/scrum/label/model/SprintLabel.java
- backend/src/main/java/minionz/backend/scrum/label/model/TaskLabel.java
- backend/src/main/java/minionz/backend/scrum/label/model/response/ReadLabelResponse.java
- backend/src/main/java/minionz/backend/scrum/label_select/SprintLabelSelectRepository.java
- backend/src/main/java/minionz/backend/scrum/label_select/TaskLabelSelectRepository.java
- backend/src/main/java/minionz/backend/scrum/label_select/model/SprintLabelSelect.java
- backend/src/main/java/minionz/backend/scrum/label_select/model/TaskLabelSelect.java
- backend/src/main/java/minionz/backend/scrum/sprint/model/Sprint.java
- backend/src/main/java/minionz/backend/scrum/task/model/Task.java
#79 #83 
<br>
- 스프린트 라벨 조회 기능을 구현했습니다.
- 태스크 라벨 조회 기능을 구현했습니다.
- 라벨 조회 시 발생할 수 있는 예외를 처리했습니다.
- 프로젝트 구조를 변경했습니다.
<br> 
- 프로젝트 구조 변경으로 인해 충돌이 발생할 수 있습니다. 확인 부탁드립니다.
close #79 
close #83
> [Feat] WORKSPACE_006, WORKSPACE_010 - 스프린트 라벨 및 태스크 라벨 조회 기능 구현 [#79, #83]

- backend/src/main/java/minionz/backend/user/EmailVerifyRepository.java
- backend/src/main/java/minionz/backend/user/EmailVerifyService.java
- backend/src/main/java/minionz/backend/user/model/EmailVerify.java
- backend/src/main/java/minionz/backend/user/model/request/EmailVerifyRequest.java
#6 
<br>
- 이메일 중복 확인 기능을 구현했습니다.
- 이메일 인증 코드 발송 기능을 구현했습니다.
<br> 
close #6
> [Feat] USER_002 - 이메일 인증 기능 [#6]

- backend/src/main/java/minionz/backend/Utils/JwtUtil.java
- backend/src/main/java/minionz/backend/config/filter/ExceptionFilter.java
- backend/src/main/java/minionz/backend/config/filter/JwtFilter.java
- backend/src/main/java/minionz/backend/config/filter/LoginFilter.java
- backend/src/main/java/minionz/backend/user/CustomUserDetailService.java
- backend/src/main/java/minionz/backend/user/VerificationTokenRepository.java
- backend/src/main/java/minionz/backend/user/model/CustomSecurityUserDetails.java
- backend/src/main/java/minionz/backend/user/model/JwtResponse.java
- backend/src/main/java/minionz/backend/user/model/VerificationToken.java
- backend/src/main/java/minionz/backend/user/model/request/LoginUserRequest.java
- backend/src/main/java/minionz/backend/user/model/request/UuidRequest.java
- backend/src/main/java/minionz/backend/user/model/request/VerificationCodeRequest.java
- backend/src/main/java/minionz/backend/user/model/response/LoginUserResponse.java
#14 
<br>
- 일반 회원가입을 한 유저 로그인 기능을 구현했습니다.
- JWT TOKEN 발행 기능을 구현했습니다.
<br> 
close #14
> [Feat] USER_003 - 일반 로그인 기능 [#14]

- backend/docker-compose.yml
<br>
- 백엔드 도커 컴포즈 파일을 구현했습니다.
<br> 
- 프론트 도커 컴포즈 파일은 아직 구현하지 못했습니다.
> [Chore] ETC - Docker-compose 구현

- backend/src/main/java/minionz/backend/common/responses/BaseResponseStatus.java
- backend/src/main/java/minionz/backend/scrum/task/TaskController.java
- backend/src/main/java/minionz/backend/scrum/task/TaskRepository.java
- backend/src/main/java/minionz/backend/scrum/task/TaskService.java
- backend/src/main/java/minionz/backend/scrum/task/model/response/ReadAllTaskResponse.java
#98 
<br>
- 한 스프린트에 속하는 태스크 목록 조회 기능을 구현했습니다.
<br> 
close #98
> [Feat] TASK_003 - 태스크 목록 조회 기능 구현 [#98]

- backend/src/main/resources/application.yml
<br>
- 그룹 id 부분 환경변수처리해서 받아오도록 yml 파일 변경했습니다.
<br> 
넣어야 하는 값은 discord에 올려뒀습니다.
> [Feat] ETC_001 그룹 아이디 환경 변수 처리

- backend/src/main/java/minionz/backend/common/responses/BaseResponseStatus.java
- backend/src/main/java/minionz/backend/scrum/meeting/MeetingController.java
- backend/src/main/java/minionz/backend/scrum/meeting/MeetingRepository.java
- backend/src/main/java/minionz/backend/scrum/meeting/MeetingService.java
- backend/src/main/java/minionz/backend/scrum/meeting/model/request/CreateMeetingRequest.java
- backend/src/main/java/minionz/backend/scrum/meeting_participation/MeetingParticipationRepository.java
- backend/src/main/java/minionz/backend/scrum/task/TaskService.java
- backend/src/main/java/minionz/backend/scrum/task/model/request/CreateTaskRequest.java
#92 
<br>
- 회의 생성 기능을 구현했습니다.
- 회의 생성한 유저를 포함한 참여자를 회의 참여 테이블에 추가했습니다.
- 회의를 진행하며 생성한 태스크에 회의와 연관 관계를 갖도록 태스크 생성 코드를 수정했습니다.
<br> 
close #92
> [Feat] MEETING_001 - 회의 생성 기능 구현 [#92]

- backend/src/main/java/minionz/backend/common/responses/BaseResponseStatus.java
- backend/src/main/java/minionz/backend/scrum/meeting/MeetingController.java
- backend/src/main/java/minionz/backend/scrum/meeting/MeetingService.java
- backend/src/main/java/minionz/backend/scrum/meeting/model/response/ReadMeetingResponse.java
#93 
<br>
- 회의 일정 단일 조회 기능을 구현했습니다.
<br> 
추후 security config 로 권한에 따른 예외 처리를 할 예정입니다.
close #93
> [Feat] MEETING_002 - 회의 단일 조회 기능 구현 [#93]

- backend/src/main/java/minionz/backend/common/responses/BaseResponseStatus.java
- backend/src/main/java/minionz/backend/scrum/issue/IssueController.java
- backend/src/main/java/minionz/backend/scrum/issue/IssueRepository.java
- backend/src/main/java/minionz/backend/scrum/issue/IssueService.java
- backend/src/main/java/minionz/backend/scrum/issue/model/Issue.java
- backend/src/main/java/minionz/backend/scrum/issue/model/request/CreateIssueRequest.java
- backend/src/main/java/minionz/backend/scrum/workspace/model/Workspace.java
- backend/src/main/java/minionz/backend/user/model/User.java
#144 
<br>
- 이슈 생성 기능을 구현했습니다.
- 이슈 생성 시 담당자를 지정할 수 있으며, 이슈의 현 상태는 true (진행 중)으로 지정했습니다.
<br> 
close #144
> [Feat] ISSUE_001 - 이슈 생성 기능 구현 [#144]

- backend/src/main/java/minionz/backend/common/responses/BaseResponseStatus.java
- backend/src/main/java/minionz/backend/scrum/meeting/MeetingRepository.java
- backend/src/main/java/minionz/backend/scrum/schedule/ScheduleController.java
- backend/src/main/java/minionz/backend/scrum/schedule/ScheduleService.java
- backend/src/main/java/minionz/backend/scrum/schedule/request/ReadScheduleRequest.java
- backend/src/main/java/minionz/backend/scrum/schedule/response/MeetingResponse.java
- backend/src/main/java/minionz/backend/scrum/schedule/response/ReadMonthlyResponse.java
- backend/src/main/java/minionz/backend/scrum/schedule/response/SprintResponse.java
- backend/src/main/java/minionz/backend/scrum/sprint/SprintRepository.java
#105 #107 
<br>
- 워크스페이스의 월별 캘린더 조회 기능을 구현했습니다.
- 로그인 한 유저의 월별 캘린더 조회 기능을 구현했습니다.
- 해당 월이 포함된 회의와 스프린트를 조회하는 기능입니다.
<br> 
close #105 
close #107
> [Feat] SCHEDULE_001, SCHEDULE_003 - 워크스페이스 월별 캘린더 조회 기능 및 개인 월별 캘린더 조회 기능 구현 [#105, #107]

- frontend/src/services/websocketService.js
- frontend/src/store/socket/chat/useChatMessageStore.js
- frontend/src/view/chat/component/ChatComponent.vue
#56 
<br>
- 채팅 기능이 작동될 수 있도록 webSocketService 를 추가했습니다.
- Stomp와의 연결을 추가했습니다.
<br>
> [Feat] Chatting_001 채팅 백엔드 연동 [#56] 

- backend/src/main/java/minionz/backend/common/responses/BaseResponseStatus.java
- backend/src/main/java/minionz/backend/scrum/dashboard/DashboardController.java
- backend/src/main/java/minionz/backend/scrum/dashboard/DashboardService.java
- backend/src/main/java/minionz/backend/scrum/dashboard/model/response/BurnTaskResponse.java
- backend/src/main/java/minionz/backend/scrum/dashboard/model/response/ReadBurndownResponse.java
#109 
<br>
- 스프린트 별 번다운 차트를 그릴 수 있도록 구현했습니다.
<br> 
close #109
> [Feat] DASHBOARD_001 - 번다운 차트 기능 구현 [#109]

- frontend/src/router/index.js
#56 
<br>
- 라우터 링크를 수정했습니다.
-
<br>
> [Refactor] chat 라우터 path 수정

- backend/src/main/java/minionz/backend/chat/chat_room/model/response/ReadMessageResponse.java
- backend/src/main/java/minionz/backend/chat/message/MessageService.java
#20 , #22 
<br>
- 채팅을 보낼 때 sender을 통해 본인이 보낸 채팅임을 확인할 수 있는 속성을 추가했습니다.
<br> 
없습니다.
> [Fix] CHAT_005,006 - 본인이 보낸 채팅을 확인 [#20, #22]

- backend/src/main/java/minionz/backend/health/HealthController.java
- cicd/Jenkinsfile-backend
- cicd/Jenkinsfile-frontend
- cicd/k8s-backend.yml
- cicd/k8s-frontend.yml
#196 
<br>
- Docker 이미지 빌드 및 푸시 단계를 포함하여 Jenkins 파일을 생성하여 CI/CD 파이프라인을 설정했습니다.
- Kubernetes YAML 파일을 구현했습니다.
- 백엔드 및 프론트엔드 애플리케이션을 위한 Deployment, Service, Ingress 설정 추가했습니다.
- 카나리아 배포 방식으로 새로운 버전의 백엔드 및 프론트엔드에 대한 트래픽을 점진적으로 라우팅하도록 구현했습니다.
- 테스트를 위한 health 컨트롤러를 구현했습니다. 
<br> 
close #196
> [Feat] K8S_CICD_001 - CI/CD 파이프라인 및 Kubernetes 배포 설정 구현 [#196]

- backend/src/main/java/minionz/backend/chat/chat_room/ChatRoomController.java
- backend/src/main/java/minionz/backend/chat/chat_room/ChatRoomService.java
- backend/src/main/java/minionz/backend/chat/message/MessageController.java
- backend/src/main/java/minionz/backend/chat/message/MessageService.java
- backend/src/main/java/minionz/backend/common/responses/BaseResponseStatus.java
#199 , #200 
<br>
- 채팅 관련 예외 처리를 구현 했습니다.
- 채팅방 관련 예외 처리를 구현 했습니다.
- 예외 처리를 통해 필요한 상태를 추가 해 뒀습니다.
<br> 
close #199 
close #200
> [Feat] CHAT_013,014 - 채팅방 및 메세지 예외 처리 기능 구현 [#199, #200]

- cicd/Jenkinsfile-backend
- cicd/Jenkinsfile-frontend
<br>
- 도커 이미지 생성을 위한 dockerfile의 명령어를 수정했습니다.
<br>
> [Refactor] 도커 이미지 생성을 위한 jenkinsfile 수정

- backend/src/main/java/minionz/backend/health/HealthController.java
<br>
- 도커 이미지 생성을 위한 dockerfile의 명령어를 수정했습니다.
<br>
> [Rename] 파일 이름 수정

- cicd/Jenkinsfile-frontend
<br>
- cicd를 위한 젠킨스 파일을 수정했습니다.
-
<br>
> [Refactor] cicd를 위한 젠킨스 파일 수정

- frontend/src/stores/chat/useChatMessageStore.js
- frontend/src/stores/chat/useChatRoomStore.js
- frontend/src/view/chat/ChatRoomPage.vue
- frontend/src/view/chat/component/ChatRoomComponent.vue
#56
<br>
- 백엔드의 kafka 서버에 연결시키기 위해 websocket과 stomp를 적용하였습니다.
<br> 
- user 정보가 여전히 더미데이터로 구성되어있습니다. 유저 목록을 반영시킨 후 채팅 목록과 채팅방 생성을 변경해야합니다.
> [Feat] FE_CHATTING_001 채팅 전송 웹소켓 적용 #56

- cicd/k8s-frontend.yml
> [Refactor] frontend-yml port 수정

- cicd/k8s-frontend.yml
> [Refactor] frontend-yml type 수정

- cicd/k8s-backend.yml
- cicd/k8s-frontend.yml
<br>
- 도메인으로 접속할 수 있도록 추가했습니다.
<br>
> [Feat] domain 추가

- cicd/Jenkinsfile-backend
> [Refactor] test

- backend/src/main/java/minionz/backend/health/HealthController.java
- cicd/Jenkinsfile-backend
- cicd/k8s-backend.yml
- frontend/src/view/dashboard/MyDashBoard.vue
<br>
- 잘못된 서비스 이름을 수정했습니다.
- 젠킨스 확인을 위한 테스트 코드를 추가했습니다.
<br>
> [Fix] k8s, cicd 관련 오류 수정

- backend/src/main/resources/application.yml
- cicd/Jenkinsfile-backend
- cicd/k8s-backend.yml
<br>
- 백엔드 배포 시 ingress 생성에 오류가 생기는 부분을 수정했습니다.
<br>
> [fix] ingress 생성 실패 오류 수정

- cicd/k8s-backend.yml
- cicd/k8s-frontend.yml
<br>
- ingress 생성 코드에 namespace를 추가했습니다.
<br>
> [fix] ingress에 namespace 추가

- backend/src/main/java/minionz/backend/common/responses/BaseResponseStatus.java
- frontend/src/view/dashboard/MyDashBoard.vue
> [Feat] 응답 메세지 구현

- backend/src/main/java/minionz/backend/common/responses/BaseResponseStatus.java
- cicd/k8s-backend.yml
- cicd/k8s-frontend.yml
- frontend/src/view/dashboard/MyDashBoard.vue
<br>
- 응답 메세지 공통 부분에 필요한 것들을 추가 했습니다.
<br> 
k8s yaml 파일에 있는 도메인 부분 수정 했습니다.
> [Feat] 응답 메세지 공통 부분 구현

- backend/src/main/java/minionz/backend/common/responses/BaseResponseStatus.java
- frontend/src/view/dashboard/MyDashBoard.vue
<br>
- 응답 메세지 공통 부분에 필요한 것들을 수정했습니다.
<br>
> [Fix] 응답 메세지 공통 부분 수정

- cicd/Jenkinsfile-backend
> [Refactor] 환경변수 전달 구현

- backend/src/main/java/minionz/backend/chat/message/MessageService.java
#20 
<br>
- 메세지 전송 부분에 예외처리 부분에 없어도 되는 예외처리가 있어서 수정 했습니다.
<br>
> [Fix] CHAT_005 메세지 예외처리 수정 [#20]

- backend/src/main/java/minionz/backend/common/responses/BaseResponseStatus.java
<br>
- 공통 상태 코드에서 필요없는 코드를 제거 했습니다.
-
<br>
> [Remove] 공통 상태 필요없는 코드 제거

- backend/src/main/java/minionz/backend/common/responses/BaseResponseStatus.java
<br>
- 필요 없는 상태 코드를 삭제했습니다.
-
<br>
> [Remove] 공통 상태 필요없는 코드 변경 및 제거

- backend/src/main/java/minionz/backend/health/HealthController.java
- cicd/k8s-backend.yml
<br>
- ingress로 백엔드에 요청할 때 api 경로를 제거하는 코드를 추가했습니다.
<br>
> [Fix] ingress 오류 수정

- backend/src/main/java/minionz/backend/health/HealthController.java
- frontend/src/view/dashboard/MyDashBoard.vue
<br>
- ingress 생성 확인을 위한 테스트 코드를 작성했습니다.
<br>
> [Test] ingress 생성 확인을 위한 테스트

- backend/src/main/java/minionz/backend/health/HealthController.java
- cicd/Jenkinsfile-backend
- cicd/Jenkinsfile-frontend
<br>
-  ingress 파일이 쿠버네티스 환경으로 transfer 되도록 파일을 추가하는 코드를 작성했습니다.
-
<br>
> [Refactor] ingress 파일 transfer 코드 추가

- cicd/Jenkinsfile-backend
- cicd/Jenkinsfile-frontend
<br>
- ingress 파일 transfer 코드 수정했습니다.
<br>
> [Refactor] ingress 파일 transfer 코드 수정

- frontend/src/view/user/pages/SignupPage.vue
<br>
- Signup Page의 코드 오류를 수정했습니다.
-
<br>
> [Fix] SignupPage 코드 수정

- backend/src/main/java/minionz/backend/health/HealthController.java
<br>
-  ingress 파일 테스트를 위한 코드를 작성했습니다.
-
<br>
> [Test] ingress 파일 테스트를 위한 코드 작성

- frontend/src/view/user/pages/SignupPage.vue
<br>
- 회원가입 페이지 출력 내용을 수정했습니다.
<br>
> [Fix] SignupPage 출력 내용 수정

- backend/src/main/java/minionz/backend/config/filter/JwtFilter.java
<br>
- k8s의 livenessProbe와 readinessProbe 동작 확인을 위한 코드를 수정했습니다.
<br>
> [Fix] Jenkins-backend test

- cicd/k8s-backend.yml
> [Fix] Jenkins backend test

- backend/src/main/java/minionz/backend/config/filter/JwtFilter.java
<br>
- JWT Filter의 Path를 수정했습니다.
<br>
> [Fix] Path 수정

- backend/src/main/java/minionz/backend/user/UserController.java
> [Fix] Jenkins-backend test용

- backend/src/main/java/minionz/backend/search/SearchController.java
- backend/src/main/java/minionz/backend/search/SearchRepository.java
- backend/src/main/java/minionz/backend/search/SearchService.java
- backend/src/main/java/minionz/backend/search/model/request/SearchUserRequest.java
- backend/src/main/java/minionz/backend/user/UserController.java
#251 
<br>
- 워크스페이스 초대를 위한 모든 유저들의 검색을 구현했습니다.
<br> 
- 추후 수정이 필요할 것입니다.
close #251
> [Feat] SEARCH_001 - 모든 유저 조회 기능

- backend/src/main/java/minionz/backend/search/model/request/WorkspaceUserRequest.java
#253 
<br>
- 같은 워크스페이스 Id 값을 가지는 유저의 조회 기능을 구현했습니다.
-
<br> 
close #253
> [Feat] SEARCH_002 - 워크스페이스 내 유저 조회 기능 #253

- backend/src/main/java/minionz/backend/alarm/AlarmService.java
- backend/src/main/java/minionz/backend/alarm/model/Alarm.java
- backend/src/main/java/minionz/backend/user/UserController.java
#28 #32 
<br>
- 전송되는 알림 메세지를 4가지 문장으로 정했습니다.
- 회원가입 api를 수정했습니다.
<br>
> [Feat] ALARM_002 - 알림 생성 및 조회 기능 수정

- frontend/src/view/user/pages/SignupPage.vue
#5 
<br>
- 회원가입 시 전달 받는 값의 참조를 수정했습니다.
<br>
> [Feat] FE_USER_001 - 회원가입 Response 값 수정 [#5]

- backend/src/main/java/minionz/backend/scrum/dashboard/DashboardController.java
- backend/src/main/java/minionz/backend/scrum/dashboard/DashboardService.java
- backend/src/main/java/minionz/backend/scrum/dashboard/model/response/ReadBurndownResponse.java
#167 
<br>
- 번다운차트 퍼센테이지 기능 추가했습니다.
<br> 
이후 ideal 퍼센테이지 추가하겠습니다.
> [Refactor] 번다운차트 퍼센테이지 추가 [#167]

- backend/src/main/java/minionz/backend/scrum/dashboard/DashboardService.java
- backend/src/main/java/minionz/backend/scrum/dashboard/model/response/ReadBurndownResponse.java
- backend/src/main/resources/application.yml
#262 
<br>
- 번다운차트 이상적인 퍼센테이지 계산 알고리즘 추가했습니다.
<br>
> [Refactor] 번다운차트 ideal 퍼센테이지 계산 추가 [#262]

- backend/src/main/java/minionz/backend/scrum/issue/IssueRepository.java
- backend/src/main/java/minionz/backend/scrum/issue/IssueService.java
- backend/src/main/java/minionz/backend/scrum/issue/model/Issue.java
- backend/src/main/java/minionz/backend/scrum/issue/model/response/ReadIssueResponse.java
- backend/src/main/java/minionz/backend/scrum/workspace/WorkspaceService.java
- backend/src/main/java/minionz/backend/scrum/workspace/model/Workspace.java
- backend/src/main/java/minionz/backend/scrum/workspace/model/request/CreateWorkspaceRequest.java
- backend/src/main/java/minionz/backend/scrum/workspace/model/response/ReadWorkspaceResponse.java
#144 #259 #260 
<br>
- issue 엔터티의 잘못된 속성을 수정하고 관련된 서비스 및 dto도 수정했습니다.
- issue 엔터티에 avatar를 추가했습니다.
<br>
> [Refactor]  ISSUE_001,002,003 - 이슈 엔터티 및 dto 수정 [#144, #259, #260]

- backend/src/main/java/minionz/backend/alarm/AlarmService.java
#32 
<br>
- 스케줄링 된 알림을 보내기 위한 메서드를 추가했습니다.
<br>
> [Feat] ALARM_002 - 알림 조회 기능 추가 [#32]

- backend/src/main/java/minionz/backend/scrum/schedule/ReminderService.java
#267 
<br>
- senderId 없이 알람을 보내도록 수정했습니다.
-
<br>
> [Refactor] ALARM_003 - 리마인드 알람 기능 수정 [#267]

- backend/src/main/java/minionz/backend/search/SearchController.java
- backend/src/main/java/minionz/backend/search/SearchRepository.java
- backend/src/main/java/minionz/backend/search/SearchService.java
- backend/src/main/java/minionz/backend/search/model/response/SearchUserResponse.java
#271 
<br>
- 유저를 검색할 수 있는 기능을 추가했습니다.
<br>
> [Feat] SEARCH_002 - 특정 유저 검색 기능 [#271]

- backend/src/main/java/minionz/backend/alarm/AlarmController.java
- backend/src/main/java/minionz/backend/board/error_board/ErrorBoardController.java
- backend/src/main/java/minionz/backend/board/error_comment/ErrorCommentController.java
- backend/src/main/java/minionz/backend/board/qa_board/QaBoardController.java
- backend/src/main/java/minionz/backend/board/qa_comment/QaCommentController.java
- backend/src/main/java/minionz/backend/chat/chat_room/ChatRoomController.java
- backend/src/main/java/minionz/backend/chat/message/MessageController.java
- backend/src/main/java/minionz/backend/config/SecurityConfig.java
- backend/src/main/java/minionz/backend/note/NoteContentController.java
- backend/src/main/java/minionz/backend/note/NoteController.java
- backend/src/main/java/minionz/backend/note/NoteService.java
- backend/src/main/java/minionz/backend/scrum/dashboard/DashboardController.java
- backend/src/main/java/minionz/backend/scrum/issue/IssueController.java
- backend/src/main/java/minionz/backend/scrum/label/LabelController.java
- backend/src/main/java/minionz/backend/scrum/meeting/MeetingController.java
- backend/src/main/java/minionz/backend/scrum/schedule/ReminderService.java
- backend/src/main/java/minionz/backend/scrum/schedule/ScheduleController.java
- backend/src/main/java/minionz/backend/scrum/sprint/SprintController.java
- backend/src/main/java/minionz/backend/scrum/task/TaskController.java
<br>
- RequestMapping의 경로를 api를 포함하도록 수정했습니다.
- @scheduled 어노테이션의 동작 시간을 10분으로 수정했습니다.
<br>
> [Refactor] api 경로 수정

- frontend/src/common/component/RightSide/RightSideIssue.vue
- frontend/src/common/component/RightSide/RightSideParticipants.vue
- frontend/src/static/workspaceDashboardData.js
- frontend/src/stores/workspace/useDashboard.js
- frontend/src/utils/meetingBgUtils.js
- frontend/src/view/dashboard/MyDashBoard.vue
- frontend/src/view/dashboard/WorkspaceDashBoard.vue
- frontend/src/view/dashboard/component/MeetingList.vue
- frontend/src/view/dashboard/component/PriorityTask.vue
<br>
- Dashboard와 관련된 store를 전부 수정하였습니다.
- yarn build 에러를 수정하였습니다.
<br>
> [Refactor] store 4차 수정

- backend/src/main/java/minionz/backend/health/HealthController.java
- cicd/k8s-frontend.yml
- frontend/src/view/user/pages/SignupPage.vue
<br>
- cicd를 위한 코드를 수정했습니다.
<br>
> [Fix] cicd를 위한 코드 수정

- cicd/Jenkinsfile-backend
> [refactor] 누락된 tag 추가

- cicd/Jenkinsfile-frontend
- frontend/Dockerfile
- frontend/src/view/dashboard/MyDashBoard.vue
<br>
-  프론트엔드 build 파일이 적용되지 않아 yarn build를 수행하는 위치를 변경했습니다.
<br>
> [Fix] frontend-yml 파일 수정 

- cicd/Jenkinsfile-frontend
- frontend/src/view/dashboard/MyDashBoard.vue
> [refactor] yarn build 하는 수행 위치 변경

- cicd/Jenkinsfile-frontend
- frontend/Dockerfile
> [refactor] rollback 

- frontend/src/view/dashboard/MyDashBoard.vue
> [refactor] 이전 코드로 rollback

- backend/src/main/java/minionz/backend/health/HealthController.java
- frontend/src/view/dashboard/MyDashBoard.vue
> [Test] cicd 테스트를 위한 공백 추가

- cicd/k8s-frontend.yml
- frontend/Dockerfile
- frontend/src/view/dashboard/MyDashBoard.vue
<br>
- conf 파일 쿠버네티스 yml에서 직접 copy하여 옮기는 것으로 수정했습니다.
<br>
> [Refactor] conf 파일 쿠버네티스 yml에서 직접 copy로 수정

- backend/src/main/java/minionz/backend/alarm/AlarmController.java
- backend/src/main/java/minionz/backend/alarm/AlarmService.java
- backend/src/main/java/minionz/backend/alarm/model/request/AlarmRequest.java
<br>
- 알림 메세지에 전송되는 변수를 추가했습니다.
<br>
> [Refactor] 알림 메세지에 변수 추가

- backend/src/main/java/minionz/backend/common/responses/BaseResponseStatus.java
- backend/src/main/java/minionz/backend/config/SecurityConfig.java
- backend/src/main/java/minionz/backend/scrum/schedule/ReminderService.java
- backend/src/main/java/minionz/backend/scrum/sprint/SprintService.java
- backend/src/main/java/minionz/backend/scrum/task/TaskService.java
- backend/src/main/java/minionz/backend/scrum/workspace/WorkspaceController.java
- backend/src/main/java/minionz/backend/scrum/workspace/WorkspaceService.java
- backend/src/main/java/minionz/backend/scrum/workspace_participation/WorkspaceParticipationRepository.java
- backend/src/main/java/minionz/backend/user_alarm/model/UserAlarm.java
#291 
<br>
- 워크스페이스 초대를 수락하는 기능을 구현했습니다.
- 워크스페이스 초대를 거절하는 기능을 구현했습니다.
- 이미 수락된 초대에 예외처리를 했습니다.
- 초대장을 보낼 때, workspaceId를 포함하도록 수정했습니다.
<br> 
워크스페이스를 생성한 유저에게도 초대장이 발송되는 이슈를 확인했습니다. 추후 수정하도록 하겠습니다.
close #291
> [Feat] WORKSPACE_005 - 워크스페이스 초대 응답 기능 구현 [#291]

- backend/src/main/java/minionz/backend/config/SecurityConfig.java
<br>
- 로그인이 이루어지는 경로를 수정했습니다.
<br>
> [Refactor] 로그인 경로 수정

- frontend/src/layouts/AppHeader.vue
- frontend/src/layouts/component/modal/AlarmModalBU.vue
- frontend/src/static/alarmData.js
- frontend/src/static/chatData.js
- frontend/src/static/meetingData.js
- frontend/src/static/taskData.js
- frontend/src/stores/socket/useAlarmStore.js
- frontend/src/stores/workspace/scrum/useTaskStore.js
- frontend/src/stores/workspace/space/useWorkspaceStore.js
- frontend/src/utils/weekSettingUtils.js
- frontend/src/view/schedule/monthly/component/MonthlyComponent.vue
- frontend/src/view/schedule/weekly/component/WeeklyScheduleComponent.vue
- frontend/src/view/scrum/Task/kanban/MyTaskKanban.vue
- frontend/src/view/scrum/Task/kanban/WorkSpaceTaskKanban.vue
- frontend/src/view/scrum/create/WorkSpaceCreate.vue
- frontend/src/view/user/component/SocialLogin.vue
- frontend/vue.config.js
<br>
- 워크스페이스 알람의 기능을 수정하였습니다.
- 각종 더미 데이터가 남아있는 부분들을 수정하였습니다.
<br>
> [Refactor] store 7차 수정

- cicd/k8s-frontend.yml
<br>
- nginx에 config map으로 default.conf 파일을 설정했습니다.
<br>
> [Refactor] cicd를 위한 conf 설정

- frontend/src/stores/my/useMypageStore.js
- frontend/src/stores/user/useUserStore.js
- frontend/src/stores/workspace/space/useWorkspaceStore.js
- frontend/src/stores/workspace/useDashboardStore.js
- frontend/src/view/scrum/Task/kanban/WorkSpaceTaskKanban.vue
Reverts beyond-sw-camp/be06-fin-MINIONZ-CalIT#298
> Revert "[Refactor] Store 및 로직 8차 수정"

- README.md
- backend/src/main/java/minionz/backend/common/responses/BaseResponseStatus.java
- backend/src/main/java/minionz/backend/config/SecurityConfig.java
- backend/src/main/java/minionz/backend/scrum/schedule/ReminderService.java
- backend/src/main/java/minionz/backend/scrum/sprint/SprintService.java
- backend/src/main/java/minionz/backend/scrum/task/TaskService.java
- backend/src/main/java/minionz/backend/scrum/workspace/WorkspaceController.java
- backend/src/main/java/minionz/backend/scrum/workspace/WorkspaceService.java
- backend/src/main/java/minionz/backend/scrum/workspace_participation/WorkspaceParticipationRepository.java
- cicd/k8s-frontend.yml
- frontend/src/layouts/AppHeader.vue
- frontend/src/layouts/component/modal/AlarmModalBU.vue
- frontend/src/static/alarmData.js
- frontend/src/static/chatData.js
- frontend/src/static/meetingData.js
- frontend/src/static/taskData.js
- frontend/src/stores/socket/useAlarmStore.js
- frontend/src/stores/workspace/scrum/useTaskStore.js
- frontend/src/stores/workspace/space/useWorkspaceStore.js
- frontend/src/utils/weekSettingUtils.js
- frontend/src/view/schedule/monthly/component/MonthlyComponent.vue
- frontend/src/view/schedule/weekly/component/WeeklyScheduleComponent.vue
- frontend/src/view/scrum/Task/kanban/MyTaskKanban.vue
- frontend/src/view/scrum/Task/kanban/WorkSpaceTaskKanban.vue
- frontend/src/view/scrum/create/WorkSpaceCreate.vue
- frontend/src/view/user/component/SocialLogin.vue
- frontend/vue.config.js
Reverts beyond-sw-camp/be06-fin-MINIONZ-CalIT#297
> Revert "[Refactor] 소셜 로그인 경로 수정"

- backend/gradlew
- backend/src/main/java/minionz/backend/alarm/AlarmController.java
- backend/src/main/java/minionz/backend/board/error_board/ErrorBoardController.java
- backend/src/main/java/minionz/backend/board/error_comment/ErrorCommentController.java
- backend/src/main/java/minionz/backend/board/qa_board/QaBoardController.java
- backend/src/main/java/minionz/backend/board/qa_comment/QaCommentController.java
- backend/src/main/java/minionz/backend/chat/chat_room/ChatRoomController.java
- backend/src/main/java/minionz/backend/chat/message/MessageController.java
- backend/src/main/java/minionz/backend/config/SecurityConfig.java
- backend/src/main/java/minionz/backend/config/filter/JwtFilter.java
- backend/src/main/java/minionz/backend/health/HealthController.java
- backend/src/main/java/minionz/backend/note/NoteController.java
- backend/src/main/java/minionz/backend/scrum/dashboard/DashboardController.java
- backend/src/main/java/minionz/backend/scrum/issue/IssueController.java
- backend/src/main/java/minionz/backend/scrum/label/LabelController.java
- backend/src/main/java/minionz/backend/scrum/meeting/MeetingController.java
- backend/src/main/java/minionz/backend/scrum/schedule/ScheduleController.java
- backend/src/main/java/minionz/backend/scrum/sprint/SprintController.java
- backend/src/main/java/minionz/backend/scrum/task/TaskController.java
- backend/src/main/java/minionz/backend/scrum/workspace/WorkspaceController.java
- backend/src/main/java/minionz/backend/search/SearchController.java
- backend/src/main/java/minionz/backend/user/UserController.java
<br>
- 백엔드 구분을 위해 달아 놓은 /api 경로를 /로 바꿨습니다.
<br>
> [Refactor] /api 경로 / 로수정

- backend/src/main/java/minionz/backend/health/HealthController.java
- cicd/k8s-ingress.yml
<br>
- rewrite 어노테이션 추가로 백엔드 서비스 연결 시 오류 해결했습니다.
<br>
> [Fix] rewrite 어노테이션 추가로 백엔드 서비스 연결 시 오류 해결

- backend/src/main/java/minionz/backend/config/SecurityConfig.java
<br>
- RequestMapping에 있는 경로 중 api를 제거하며 권한 확인에서 오류가 발생하여 수정했습니다.
<br>
> [Fix] api 경로 수정으로 인한 에러 수정

- frontend/src/view/user/component/SocialLogin.vue
<br>
- 소셜 로그인 경로를 수정했습니다.
<br>
> [Refactor] 소셜 로그인 경로 수정

- backend/src/main/resources/application.yml
<br>
- yaml파일 경로를 수정했습니다.
<br>
> [Refactor] yaml파일 경로 수정

- backend/src/main/java/minionz/backend/config/filter/LoginFilter.java
- backend/src/main/java/minionz/backend/config/filter/OAuth2AuthenticationSuccessHandler.java
- backend/src/main/java/minionz/backend/search/SearchController.java
- backend/src/main/java/minionz/backend/search/SearchRepository.java
- backend/src/main/java/minionz/backend/search/SearchService.java
- backend/src/main/java/minionz/backend/search/model/response/SearchUserResponse.java
- backend/src/main/java/minionz/backend/utils/JwtUtil.java
<br>
- 토큰에 저장되는 유저 정보를 변경했습니다.
<br>
> [Refactor] 토큰에 저장되는 유저 정보 변경

- backend/src/main/java/minionz/backend/health/HealthController.java
- cicd/k8s-backend.yml
<br>
- 백엔드 파드가 계속해서 connection counfused 상태가 되어 liveness와 readiness 의 실행 시간을 조정했습니다. 
<br>
> [Refactor] health check 타임 조정

- backend/src/main/java/minionz/backend/health/HealthController.java
- cicd/k8s-backend.yml
<br>
- k8s service에 스티키 세션을 적용했습니다.
<br>
> [Refactor] 스티키 세션 적용

- cicd/k8s-frontend.yml
- frontend/src/view/user/pages/SignupPage.vue
<br>
- 프론트 엔드 서비스에 스티키 세션을 적용했습니다.
<br>
> [Refactor] 프론트 엔드 서비스 스티키 세션 적용

- backend/src/main/java/minionz/backend/config/filter/JwtFilter.java
- backend/src/main/java/minionz/backend/scrum/workspace/WorkspaceController.java
- backend/src/main/java/minionz/backend/scrum/workspace/WorkspaceService.java
- backend/src/main/java/minionz/backend/scrum/workspace/model/request/CreateWorkspaceRequest.java
- backend/src/main/java/minionz/backend/utils/JwtUtil.java
<br>
- token 생성 수정으로 인한 오류를 해결하기 위해 jwt util의 user 생성을 수정했습니다.
<br>
> [Fix] jwt util 수정

- cicd/Jenkinsfile-backend
- cicd/Jenkinsfile-frontend
<br>
- 젠킨스 디스코드 환경변수명을 변경했습니다.
<br>
> [Refactor] 젠킨스 디스코드 환경변수명 변경

- cicd/Jenkinsfile-backend
- cicd/Jenkinsfile-frontend
<br>
- 젠킨스 디스코드 코드를 수정했습니다.
<br>
> [Feat] 젠킨스 디스코드 코드 수정

- backend/src/main/java/minionz/backend/alarm/AlarmController.java
- backend/src/main/java/minionz/backend/alarm/AlarmService.java
- backend/src/main/java/minionz/backend/alarm/model/response/ReadMyAlarmResponse.java
- backend/src/main/java/minionz/backend/common/responses/BaseResponseStatus.java
- backend/src/main/java/minionz/backend/scrum/sprint/SprintController.java
- backend/src/main/java/minionz/backend/scrum/sprint/SprintService.java
- backend/src/main/java/minionz/backend/scrum/task/TaskController.java
- backend/src/main/java/minionz/backend/scrum/task/TaskService.java
- backend/src/main/java/minionz/backend/scrum/workspace/WorkspaceController.java
- backend/src/main/java/minionz/backend/scrum/workspace/WorkspaceService.java
- backend/src/main/java/minionz/backend/user_alarm/UserAlarmRepository.java
- backend/src/main/java/minionz/backend/user_alarm/model/UserAlarm.java
<br>
- 로그인한 유저의 알람 리스트 조회 기능을 구현했습니다. 
<br>
> [Feat] 로그인 한 유저의 알람 조회 기능 구현

- frontend/src/layouts/component/modal/AlarmModal.vue
- frontend/src/layouts/component/modal/ChatModal.vue
- frontend/src/stores/socket/useAlarmStore.js
<br>
- alarm 전송의 api가 수정되었습니다.
<br>
> [Refactor] alarm api 수정

- frontend/src/layouts/component/modal/AlarmModal.vue
- frontend/src/stores/socket/useAlarmStore.js
<br>
- alarm을 호출하는 api 경로와 메소드가 수정되었습니다.
-
<br>
> [Refactor] alarm api 경로 및 메소드 수정

- cicd/Jenkinsfile-backend
<br>
- 젠킨스 디스코드 코드 들여쓰기를 수정했습니다.
<br>
> [Feat] 젠킨스 디스코드 코드 들여쓰기 수정

- frontend/src/layouts/component/modal/AlarmModal.vue
- frontend/src/view/scrum/Task/kanban/MyTaskKanban.vue
<br>
- alarm api 경로 및 유저 정보 전달 값을 수정하였습니다.
-
<br>
> [Refactor] alarm 메소드 수정

- cicd/Jenkinsfile-frontend
<br>
- 젠킨스 디스코드 코드 환경변수를 수정했습니다.
<br>
> [Feat] 젠킨스 디스코드 코드 환경변수 수정

- cicd/Jenkinsfile-backend
- cicd/Jenkinsfile-frontend
<br>
-  젠킨스 디스코드 코드 전송 메세지를 수정했습니다.
<br>
> [Refactor] 젠킨스 디스코드 코드 전송 메세지 수정

- frontend/src/stores/socket/useAlarmStore.js
> [Refactor] alarm patch 경로 수정

- frontend/src/router/index.js
- frontend/src/stores/user/useUserStore.js
- frontend/src/stores/workspace/space/useWorkspaceStore.js
- frontend/src/view/user/pages/SocialLoginSuccessPage.vue
> [Feat] Social Login Success Page add

- backend/src/main/java/minionz/backend/config/filter/OAuth2AuthenticationSuccessHandler.java
<br>
- 백엔드에서 로그를 찍는 코드를 추가했습니다.
<br>
> [Refactor] 백엔드 로그 찍기 추가

- backend/src/main/java/minionz/backend/config/SecurityConfig.java
- backend/src/main/resources/application.yml
<br>
- 구글 yml redirect uri 삭제헀습니다.
<br>
> [Refactor] 구글 yml redirect uri 삭제

- backend/src/main/java/minionz/backend/health/HealthController.java
- backend/src/main/resources/application.yml
<br>
- 구글 yml redirect uri 변경했습니다.
<br>
> [Refactor] 구글 yml redirect uri 변경

- backend/src/main/java/minionz/backend/config/filter/OAuth2AuthenticationSuccessHandler.java
- backend/src/main/resources/application.yml
> [Refactor] 구글 시크릿키값 수정

- backend/src/main/java/minionz/backend/health/HealthController.java
- cicd/Jenkinsfile-backend
- cicd/Jenkinsfile-frontend
<br>
- 작업 분리를 위한 파이프라인 변경으로 폴더 이름을 수정했습니다.
-
<br>
> [Refactor] 젠킨스 파이프라인 이름 변경

- backend/src/main/java/minionz/backend/config/SecurityConfig.java
- backend/src/main/java/minionz/backend/config/filter/OAuth2AuthenticationFailureHandler.java
<br>
- OAuth2AuthenticationFailureHandler를 추가했습니다.
<br>
> [Feat] OAuth2AuthenticationFailureHandler 추가

- frontend/src/view/user/pages/SocialLoginSuccessPage.vue
<br>
- social login의 authorization 토큰 설정 로직을 수정했습니다.
<br>
> [Refactor] social login authorization 경로 수정

- backend/src/main/java/minionz/backend/common/responses/BaseResponseStatus.java
- backend/src/main/java/minionz/backend/search/SearchController.java
<br>
- 검색 기능의 응답 타입을 수정했습니다.
<br>
> [Refactor] 검색 기능 응답 타입 수정

- frontend/src/common/component/Board/ScrumList.vue
- frontend/src/common/component/search/SearchFriends.vue
- frontend/src/stores/scrum/useSprintStore.js
- frontend/src/stores/user/useFriendsStore.js
- frontend/src/view/scrum/create/SprintCreatePage.vue
- frontend/src/view/scrum/list/SprintListPage.vue
- frontend/src/view/user/pages/SocialLoginSuccessPage.vue
<br>
- 소셜 로그인 토큰 값을 가져오기 위해 콘솔을 찍었습니다
<br>
> [Refactor] social login redirection

- frontend/src/App.vue
- frontend/src/router/index.js
- frontend/src/view/user/pages/SocialLoginSuccessPage.vue
<br>
- 소셜로그인 set token을 위한 페이지 로직 수정
<br>
> [Refactor] social login set token

- backend/src/main/java/minionz/backend/config/swagger/SwaggerConfig.java
- backend/src/main/resources/application.yml
<br>
- Swagger Config를 수정했습니다.
<br>
> [Feat] Swagger Config 수정

- backend/src/main/java/minionz/backend/health/HealthController.java
- backend/src/main/resources/application.yml
<br>
- Swagger Config를 수정했습니다.
<br>
> [Refactor] Swagger Config 수정

- backend/src/main/java/minionz/backend/config/SecurityConfig.java
- backend/src/main/java/minionz/backend/scrum/sprint/SprintController.java
- backend/src/main/java/minionz/backend/scrum/workspace/WorkspaceController.java
- backend/src/main/java/minionz/backend/user/CustomUserDetailService.java
- backend/src/main/java/minionz/backend/user/UserService.java
- backend/src/main/java/minionz/backend/user/model/CustomSecurityUserDetails.java
- backend/src/main/java/minionz/backend/utils/JwtUtil.java
<br>
- 워크스페이스 생성 혹은 참여, 스프린트 생성 등 새로 참여하는 경우 토큰을 재발행해서 role을 업데이트 해주도록 수정했습니다.
- 권한 확인 시 권한이 없을 경우, 스프린트나 태스크, 회의에 할당됐을 경우를 생각하여 다시 권한을 확인하고 토큰을 발행하고 권한을 허용하도록 수정했습니다.
<br>
> [Feat] 토큰 재발행 기능 구현

- frontend/src/layouts/SideBar.vue
- frontend/src/layouts/component/modal/WorkspaceModal.vue
- frontend/src/main.js
- frontend/src/router/index.js
- frontend/src/stores/scrum/useSprintStore.js
- frontend/src/stores/user/useFriendsStore.js
- frontend/src/stores/workspace/useWorkspaceStore.js
- frontend/src/view/dashboard/WorkspaceDashBoardPage.vue
- frontend/src/view/scrum/create/SprintCreatePage.vue
- frontend/src/view/scrum/create/WorkSpaceCreatePage.vue
<br>
- workspaceId와 workspace와 sprint, 로직들을 수정했습니다.
<br>
> [Refactor] router, sprint, workspace 관련 로직 수정

- frontend/src/layouts/component/modal/WorkspaceModal.vue
<br>
- 빌드 에러로 인하여 @click을 수정하였습니다.
<br>
> [Refactor] 빌드 에러로 인한 workspace click 수정

- backend/build.gradle
- backend/src/main/java/minionz/backend/chat/chat_bot/ChatBotController.java
- backend/src/main/java/minionz/backend/chat/chat_bot/ChatBotRepository.java
- backend/src/main/java/minionz/backend/chat/chat_bot/ChatBotService.java
- backend/src/main/java/minionz/backend/chat/chat_bot/model/ChatBot.java
- backend/src/main/java/minionz/backend/chat/chat_bot/model/request/ChatBotRequest.java
- backend/src/main/java/minionz/backend/user/model/User.java
- backend/src/main/resources/application.yml
#371 
<br>
- 사용자가 질문을 요청 시, Gemini API를 통해 대답을 받아오는 기능을 구현했습니다.
- 여기에서 성능 개선 방향으로 가기 위해 다른 방법을 도입 할 예정입니다. 
<br> 
gpt가 아니라 Gemini를 쓴 이유는 Gemini는 구글이라서 학습한 데이터가 많아서 그런지 길게 대답해주는 느낌을 받았습니다. 사용 해 보고 변경이 필요하면 변경하겠습니다.
discord에 api-key 부분을 올려두었고, 복사해서 쓰시면 됩니다.
> [Feat] CHATBOT_001 - 챗봇 질문 및 대답 기능 구현 [#371]

- backend/src/main/java/minionz/backend/config/SecurityConfig.java
- backend/src/main/java/minionz/backend/note/NoteConsumer.java
- backend/src/main/java/minionz/backend/note/NoteContentController.java
- backend/src/main/java/minionz/backend/note/NoteController.java
- backend/src/main/java/minionz/backend/note/NoteProducer.java
- backend/src/main/java/minionz/backend/note/NoteService.java
- backend/src/main/java/minionz/backend/note/model/response/GetNoteAllResponse.java
- backend/src/main/java/minionz/backend/scrum/label_select/model/NoteLabelSelect.java
- backend/src/main/java/minionz/backend/scrum/meeting/MeetingController.java
- backend/src/main/java/minionz/backend/scrum/meeting/MeetingRepository.java
- backend/src/main/java/minionz/backend/scrum/meeting/MeetingService.java
- backend/src/main/java/minionz/backend/scrum/meeting/model/Meeting.java
- backend/src/main/java/minionz/backend/scrum/meeting/model/response/ReadAllMeetingResponse.java
- backend/src/main/java/minionz/backend/scrum/meeting/model/response/ReadLabelResponse.java
- backend/src/main/java/minionz/backend/scrum/sprint/model/response/Participant.java
#7 
<br>
-회의와 회의록 관련 조회 기능 수정했습니다.
<br>
> [Refactor] 회의 조회 기능 수정 [#7]

- backend/src/main/java/minionz/backend/user/model/CustomOauth2UserDetails.java
<br>
- 소셜 로그인시 반환 토큰을 수정했습니다.
<br>
> [Refactor] 소셜 로그인 반환 토큰 수정

- backend/build.gradle
- backend/src/main/java/minionz/backend/config/RedisConfig.java
- backend/src/main/java/minionz/backend/scrum/meeting/MeetingController.java
- backend/src/main/java/minionz/backend/scrum/meeting/MeetingService.java
- backend/src/main/java/minionz/backend/scrum/meeting/model/response/CreateMeetingResponse.java
- backend/src/main/resources/application.yml
#92 
<br>
- 회의 생성시 id 반환 수정했습니다.
- 회의록에 redis 캐싱 적용했습니다.
<br> 
redis 동시성 처리 들어갈 예정입니다.
> [Refactor] 회의 생성 기능 수정 #92

- frontend/src/layouts/component/modal/AlarmModal.vue
- frontend/src/main.js
- frontend/src/stores/alarm/useAlarmStore.js
<br>
- 워크스페이스 수락/거절 기능 및 알림 삭제 기능을 추가했습니다.
<br>
> [Feat] 워크스페이스 수락/거절 기능 및 알림 삭제 기능 추가

- frontend/src/common/component/Board/SprintList.vue
- frontend/src/router/index.js
- frontend/src/stores/scrum/useSprintStore.js
- frontend/src/stores/scrum/useTaskStore.js
- frontend/src/stores/user/useFriendsStore.js
- frontend/src/view/scrum/Task/component/TaskViewBar.vue
- frontend/src/view/scrum/Task/create/WorkSpaceTaskCreatePage.vue
- frontend/src/view/scrum/Task/kanban/WorkSpaceTaskKanbanPage.vue
- frontend/src/view/scrum/create/WorkSpaceCreatePage.vue
- frontend/src/view/scrum/detail/IssueDetailPage.vue
- frontend/src/view/scrum/detail/SprintDetailPage.vue
<br>
- 워크스페이스 생성 시 참여자 persona를 정상적으로 그릴 수 있도록 수정했습니다.
- 스프린트 목록 조회 및 스프린트 상세 조회에서 잘못된 url 및 파라미터를 수정했습니다.
<br>
> [Refactor] 워크스페이스 및 스프린트 수정

- backend/api-server/src/main/java/minionz/apiserver/board/error_board/ErrorBoardController.java
- backend/api-server/src/main/java/minionz/apiserver/board/error_board/ErrorBoardRepository.java
- backend/api-server/src/main/java/minionz/apiserver/board/error_board/ErrorBoardService.java
- backend/api-server/src/main/java/minionz/apiserver/board/qa_board/QaBoardController.java
- backend/api-server/src/main/java/minionz/apiserver/board/qa_board/QaBoardRepository.java
- backend/api-server/src/main/java/minionz/apiserver/board/qa_board/QaBoardService.java
- backend/api-server/src/main/java/minionz/apiserver/common/responses/BaseResponseStatus.java
#21 
<br>
- 조회기능 id 반환 수정했습니다.
<br>
> [Refactor] 게시글 조회 기능 수정 [#21]

- backend/api-server/src/main/java/minionz/apiserver/chat/message/MessageController.java
- backend/api-server/src/main/java/minionz/apiserver/chat/message/MessageRepository.java
- backend/api-server/src/main/java/minionz/apiserver/chat/message/MessageService.java
- backend/api-server/src/main/java/minionz/apiserver/chat/message/model/request/SendMessageRequest.java
#150 , #172 
<br>
- 채팅 내역 받아올 때 페이징 처리 했습니다.
- 프론트와 받는 값을 맞추기 위해 파일 보낼 때의 반환값을 수정 했습니다.
<br> 
없습니다
> [Refactor] CHAT_005,007 - 파일 보내기 수정 및 채팅 내역 페이징처리 [#150, #172]

- backend/api-server/Dockerfile
- cicd/Jenkinsfile-backend
<br>
- 모듈화 후 젠킨스 자동화를 위한 설정을 적용했습니다.
<br>
> [Refactor] 모듈화 후 젠킨스 자동화 설정

- cicd/Jenkinsfile-backend
<br>
- 모듈화 후 젠킨스 자동화를 위한 설정을 수정했습니다.
<br>
> [Refactor] 모듈화 후 젠킨스 자동화 설정 수정

- backend/api-server/src/main/java/minionz/apiserver/alarm/AlarmService.java
- backend/common/src/main/java/minionz/common/alarm/model/response/ReadMyAlarmResponse.java
- backend/common/src/main/java/minionz/common/user_alarm/model/UserAlarm.java
<br>
- 알림 데이터의 타입을 Integer에서 Long으로 변경했습니다.
<br>
> [Refactor] 알림 데이터 타입 변경

- frontend/src/stores/workspace/useWorkspaceDashboardStore.js
- frontend/src/stores/workspace/useWorkspaceStore.js
- frontend/src/view/dashboard/WorkspaceDashBoardPage.vue
- frontend/src/view/dashboard/component/MeetingList.vue
- frontend/src/view/dashboard/component/WorkspaceTaskOverview.vue
- frontend/src/view/schedule/monthly/WorkSpaceMonthly.vue
- frontend/src/view/schedule/monthly/component/MonthlyComponent.vue
<br>
- 워크스페이스 대시보드 기능을 수정했습니다. 
<br>
> [Fix] 워크스페이스 대시보드 기능 수정

- frontend/src/view/dashboard/MyDashBoardPage.vue
<br>
- 나의 대시보드에서 조건에 따라 화면에 나오는 값을 알맞게 수정했습니다.
<br>
> [Refactor] 대시보드에서 조건에 따라 화면에 나오는 값 수정

- backend/api-server/src/main/java/minionz/apiserver/board/error_board/ErrorBoardController.java
- backend/api-server/src/main/java/minionz/apiserver/board/qa_board/QaBoardController.java
- backend/api-server/src/main/java/minionz/apiserver/common/responses/BaseResponseStatus.java
- backend/api-server/src/main/java/minionz/apiserver/scrum/task/TaskController.java
- backend/api-server/src/main/java/minionz/apiserver/scrum/task/TaskService.java
- backend/api-server/src/main/java/minionz/apiserver/search/SearchService.java
#3
<br>
- 태스크와 게시판 부분 코드 수정했습니다.
<br>
> [Refactor] task와 board 수정 [#3]

- frontend/src/common/component/Board/BoardList.vue
- frontend/src/common/component/RightSide/RighSideQaParticipants.vue
- frontend/src/common/component/search/SearchQaFriends.vue
- frontend/src/stores/board/useErrorStore.js
- frontend/src/stores/board/useQAStore.js
- frontend/src/stores/scrum/useTaskStore.js
- frontend/src/stores/user/useFriendsStore.js
- frontend/src/view/board/create/ErrorCreatePage.vue
- frontend/src/view/board/create/QACreatePage.vue
- frontend/src/view/board/list/ErrorListPage.vue
- frontend/src/view/board/list/QAListPage.vue
<br>
- 에러게시판 생성 전체조회 기능 구현했습니다.
<br> 
qa게시판 생성할 때 태스크와 담당자 지정까지 완료했습니다.
> [Refactor] 게시판 생성 및 조회 기능 수정

- backend/api-server/src/main/java/minionz/apiserver/scrum/schedule/ScheduleController.java
<br>
- 워크스페이스 주간 조회 시, response의 메세지가 잘못되어 수정했습니다.
<br>
> [Refactor] response message 수정

- frontend/src/stores/myspace/useMyDashboardStore.js
- frontend/src/stores/workspace/useWorkspaceDashboardStore.js
<br>
- monthly 날짜 setting 로직을 변경하였습니다.
<br>
> [Refactor] time setting utils 수정

- backend/api-server/src/main/java/minionz/apiserver/scrum/task/TaskController.java
- backend/common/src/main/java/minionz/common/scrum/task/TaskRepository.java
- backend/common/src/main/java/minionz/common/scrum/task/model/Task.java
- backend/common/src/main/java/minionz/common/scrum/workspace/model/Workspace.java
#53 
<br>
- 태스크 조회 수정했습니다.
<br>
> [Refactor] task 수정 [#53]

- frontend/src/view/schedule/monthly/component/MonthlyComponent.vue
- frontend/src/view/schedule/weekly/component/WeeklyIssues.vue
- frontend/src/view/schedule/weekly/component/WeeklyTasks.vue
<br>
- weekly, monthly의 undefined 값을 방지하고 props 연결을 수정하였습니다.
<br>
> [Refactor] weekly, monthly undefined 및 props 수정

- frontend/src/view/scrum/create/IssueCreatePage.vue
<br>
- workspaceId 를 받아올 때, useRouter로 가져와서 값을 못가져오는 문제가 있었습니다. useRoute를 사용해서 올바르게 값을 가져올 수 있도록 수정했습니다. 
- 참여자를 찾을 때 오류가 발생하여 수정했습니다. 
<br> 
ui 구현이 추가적으로 필요합니다.
> [Fix] 이슈 생성 오류 수정

- frontend/src/stores/scrum/useIssueStore.js
- frontend/src/view/scrum/create/IssueCreatePage.vue
<br>
- 이슈 생성 시 잘못된 매개변수를 전달하는 store 및 component를 수정하여 올바른 api 요청을 하도록 수정했습니다.
- 누락된 ui를 이전 코드에서 백업해 와서 요구사항에 맞게 수정했습니다.
<br>
> [Fix] 이슈 생성 에러 수정

- frontend/src/view/scrum/create/WorkSpaceCreatePage.vue
<br>
- 워크스페이스 생성 시 참여자 추가 할 때 생기는 에러 해결
-
<br>
> [Fix] 워크스페이스 생성 오류 해결

- .gitignore
- frontend/src/main.js
<br>
- 알림 연결이 되는 주소를 배포 환경으로 수정했습니다.
<br>
> [Refactor] 알림 연결이 되는 주소를 배포 환경으로 수정

- backend/api-server/src/main/java/minionz/apiserver/user/model/CustomOauth2UserDetails.java
<br>
- 소셜 로그인 권한 추가 기능을 수정했습니다.
<br>
> [Refactor] 소셜 로그인 권한 추가 기능 수정

- frontend/src/common/component/Editor/QuillEditorMeeting 2.vue
- frontend/src/common/component/Editor/QuillEditorMeeting.vue
- frontend/src/view/chat/component/ChatRoomComponent.vue
<br>
- 로컬 환경에서 테스트 하고, 배포 환경으로 옮겼을 때 WebSocket이 http로 구성 되어 있어 돌아가지 않음을 발견 했습니다. 이를 해결하기 위해 websocket 주소를 변경함으로써 관리할 수 있도록 주소를 변경 해 뒀습니다.
-
<br>
> [Fix] 배포 환경 websocket api 경로 수정

- frontend/src/common/component/Editor/QuillEditorMeeting.vue
<br>
- api 경로 작성 부분에서 난 에러를 해결 했습니다.
-
<br>
> [Refactor] 회의록 공동 작성 부분 에러 해결

- frontend/src/common/component/Editor/QuillEditorMeeting.vue
#425 
<br>
- 회의록 공동작성 관련 수정했습니다.
<br>
> [Refactor] 회의록 공동작성 페이지 수정 [#425]

- backend/api-server/src/main/java/minionz/apiserver/note/NoteConsumer.java
- backend/api-server/src/main/java/minionz/apiserver/note/NoteContentController.java
- backend/api-server/src/main/java/minionz/apiserver/note/NoteController.java
- backend/api-server/src/main/java/minionz/apiserver/note/NoteProducer.java
#425 
<br>
- 회의록 공동작성 부분 기능 수정했습니다.
<br>
> [Refactor] 회의록 로직 수정 [#425]

- backend/api-server/src/main/java/minionz/apiserver/common/responses/BaseResponseStatus.java
- backend/api-server/src/main/java/minionz/apiserver/user/UserController.java
- backend/api-server/src/main/java/minionz/apiserver/user/UserService.java
- backend/api-server/src/main/java/minionz/apiserver/user/model/request/SocialLoginIdRequest.java
- backend/common/src/main/java/minionz/common/user/UserRepository.java
<br>
- 소셜 로그인시 loginID를 설정하는 기능을 추가했습니다.
<br>
> [Feat] 소셜 로그인 loginID 설정 기능

- backend/api-server/src/main/java/minionz/apiserver/scrum/schedule/ReminderService.java
<br>
- 스프링 배치로 알람 코드를 변경하며 발생한 에러를 주석 처리 해뒀습니다. 
<br>
> [Fix] 스프링 배치로 변경하며 코드 변경으로 이한 에러 주석 처리

- frontend/src/layouts/AppHeader.vue
- frontend/src/router/index.js
<br>
- chatbot의 url을 my 하위로 수정하였습니다.
<br>
> [Refactor] chatbot url 재수정

- frontend/src/utils/alarmUtils.js
<br>
- alarmUtils에서 사용할 url을 수정하였습니다.
<br>
> [Refactor] alarmUtils.js 수정

- backend/api-server/src/main/java/minionz/apiserver/chat/chat_bot/ChatBotController.java
- backend/api-server/src/main/java/minionz/apiserver/chat/chat_bot/ChatBotService.java
- backend/common/src/main/java/minionz/common/chat/chat_bot/model/ChatBot.java
- backend/common/src/main/java/minionz/common/user/model/User.java
#432 
<br>
- N8N으로부터 받아오는 값의 json 형태를 바꿔주었습니다.
- 유저랑 챗봇의 연관 관계를 1:N으로 수정하였다.
<br> 
현재 변경 후 올려서 유니크 키가 사라져야 하는데, 혹 사라지지 않을시 테스트 후 유니크 삭제 해두도록 하겠습니다.
> [Refactor] CHATBOT_001 - 챗봇 N8N 연결 및 경로 수정 [#432]

- frontend/src/view/scrum/create/WorkSpaceCreatePage.vue
<br>
- if문의 조건을 수정해서 유저 검색시 발생하는 에러를 수정했습니다.
<br>
> [Fix] 조건부 수정

- backend/api-server/src/main/java/minionz/apiserver/search/SearchService.java
<br>
- Persona 반환값을 수정했습니다.
<br>
> [Refactor] Persona 반환 수정

- frontend/src/layouts/AppHeader.vue
- frontend/src/router/index.js
- frontend/src/stores/chatbot/useChatBotStore.js
- frontend/src/view/chat/component/ChatRoomComponent.vue
- frontend/src/view/chatbot/ChatBotPage.vue
- frontend/src/view/chatbot/ChatMessage.vue
<br>
- 챗봇 화면 구성에서 /chatbot/userId 로 접속되는 경로를 /chatbot으로 변경 했습니다.
- 챗봇 메세지 보낼 때 userId를 useUserStore에서 받아오도록 경로 변경 했습니다.
- 챗봇 화면 구성을 일단 채팅화면과 같게 구성 했습니다.
<br>
> [Feat] 챗봇 프론트 화면 구성

- backend/api-server/src/main/java/minionz/apiserver/chat/chat_bot/ChatBotController.java
#371 
<br>
- chatbot으로 오는 응답을 json형태로 매핑하여 보내줄 수 있도록 변경했습니다.
<br>
> [Fix] CHATBOT_001 - n8n응답 json 매핑 [#371]

- backend/api-server/src/main/java/minionz/apiserver/chat/chat_bot/ChatBotController.java
- backend/api-server/src/main/java/minionz/apiserver/chat/chat_bot/ChatBotService.java
- backend/api-server/src/main/java/minionz/apiserver/chat/chat_bot/model/response/ReadChatBotResponse.java
- backend/api-server/src/main/java/minionz/apiserver/common/responses/BaseResponseStatus.java
- backend/common/src/main/java/minionz/common/chat/chat_bot/ChatBotRepository.java
#449 
<br>
- userId로 챗봇 채팅 내역을 받아올 수 있도록 구현 했습니다.
- 상태 코드에 챗봇 채팅 내역 조회 관련으로 추가 해 뒀습니다.
<br> 
close #449
> [Feat] CHATBOT_002 - 챗봇 채팅 내역 조회 기능 [#449]

- frontend/src/view/chatbot/ChatMessage.vue
<br>
- 채팅이 올 때 \n이 해당 안 돼서 \n이 올 시에 <br>로 변경 되도록 했습니다.
- 채팅 봇 이미지 또한 변경 완료 했습니다.
<br>
> [Refactor] 챗봇 대화 이미지 수정 및 대화 엔터 적용

- backend/api-server/src/main/java/minionz/apiserver/scrum/label/model/request/CreateLabelRequest.java
- backend/api-server/src/main/java/minionz/apiserver/scrum/label/model/request/CreateMeetingLabelRequest.java
- backend/api-server/src/main/java/minionz/apiserver/scrum/label/model/response/ReadLabelResponse.java
- backend/api-server/src/main/java/minionz/apiserver/scrum/label/model/response/ReadMeetingLabelResponse.java
- backend/api-server/src/main/java/minionz/apiserver/scrum/sprint/model/response/Label.java
- backend/common/src/main/java/minionz/common/board/error_board/model/ErrorBoard.java
- backend/common/src/main/java/minionz/common/board/error_comment/model/ErrorComment.java
- backend/common/src/main/java/minionz/common/board/qa_board/model/QaBoard.java
- backend/common/src/main/java/minionz/common/board/qa_comment/model/QaComment.java
- backend/common/src/main/java/minionz/common/chat/message/model/Message.java
- backend/common/src/main/java/minionz/common/note/model/Note.java
- backend/common/src/main/java/minionz/common/scrum/label/model/NoteLabel.java
- backend/common/src/main/java/minionz/common/scrum/label/model/SprintLabel.java
- backend/common/src/main/java/minionz/common/scrum/label/model/TaskLabel.java
- backend/common/src/main/java/minionz/common/scrum/meeting/model/Meeting.java
- backend/common/src/main/java/minionz/common/scrum/task/model/Task.java
<br>
- Contents 같은 많은 문자열이 필요한 타입을 LONGTEXT 타입으로 변경 했습니다.
- Label 경우 Color을 String으로 받고 있었는데 Integer 형태로 변경 했습니다.
<br> 
ddl-auto 가 자동으로 되지 않는 것 같아서 LONGTEXT 경우 K8S DB에 수동으로 변경 하겠습니다.
> [Fix] 엔티티 타입 수정 및 반환값 타입 수정

- frontend/src/stores/user/useUserStore.js
- frontend/src/view/user/pages/LoginPage.vue
> [Refactor] 로그인 로직 수정

- backend/api-server/src/main/java/minionz/apiserver/config/SecurityConfig.java
- backend/api-server/src/main/java/minionz/apiserver/config/filter/CustomLogoutHandler.java
<br>
- Logout 기능을 추가했습니다.
-
<br>
> [Feat] Logout 기능 추가

- frontend/src/layouts/SideBar.vue
<br>
- 로그아웃 버튼 경로를 수정했습니다.
<br>
> [Refactor] 로그아웃 경로 수정

- backend/batch/Dockerfile
- cicd/Jenkinsfile-batch
- cicd/k8s-batch.yml
<br>
- 스프링 배치 모듈에서 스프린트, 미팅, 태스크 리마인더 잡을 주기적으로 실행하기 위해 CronJob 기반의 쿠버네티스 YAML 파일을 작성했습니다.
- 스프링 배치 애플리케이션을 컨테이너화하기 위해 Dockerfile을 작성하고, 이를 사용해 도커 이미지를 빌드한 후 도커 레지스트리로 Push하는 작업을 완료했습니다.
- 스프링 배치의 무중단 배포를 위해 Jenkins 파이프라인을 임시로 구성했습니다. 현재는 무중단 배포를 목표로 Blue-Green 배포 전략을 염두에 두고 작업 중입니다.
<br> 
현재 스프링 배치를 Blue-Green 무중단 배포 방식으로 적용하기 위해 Jenkins 파이프라인을 수정 중입니다. 이를 위해 Blue-Green 배포에 필요한 추가적인 쿠버네티스 YAML 파일이 필요하며, 해당 파일은 아직 완벽히 구현되지 않은 상태입니다. 이후 수정 및 테스트가 필요합니다.
> [Feat] 스프링 배치 크론잡 및 Blue-Green 무중단 배포 설정 초기 구현

- backend/api-server/src/main/java/minionz/apiserver/config/SecurityConfig.java
<br>
- Logout URL을 수정했습니다.
<br>
> [Refactor] Logout URL 수정

- frontend/src/main.js
<br>
-  알림 요청 시간을 수정했습니다.
<br>
> [Refactor] 알림 요청 시간 수정

- frontend/src/main.js
- frontend/src/view/chat/ChatInitialPage.vue
- frontend/src/view/chat/component/ChatComponent.vue
- frontend/src/view/chat/component/ChatRoomList.vue
<br>
- 채팅방 리스트에서 파일 목록 또한 받아오고 있는데, 이를 없애고 채팅방 목록 확인하는 창을 더 늘렸습니다.
- 안 읽은 메세지를 받아오는 목록에서 받는 값이 없기에, unreadMessages 총합을 받아오도록 구현 해 두었습니다.
<br> 
main.js에서 알람 받아오는 부분에서 디버깅이 안 될 정도로 알람이 뜨길래, 시간을 x20 해뒀습니다.
> [Fix] 채팅방 리스트 기능 수정

- frontend/src/stores/chat/useChatRoomStore.js
- frontend/src/view/chat/component/FriendsModal.vue
<br>
- 로컬 환경에서 테스트 시 채팅방을 생성할 때, 참여자의 이름으로 변경 되어 생성 되고 있었습니다.
- 속성명이 다른 문제점을 파악하고 이를 고쳐 두었습니다.
<br>
> [Fix] 채팅방 생성 받는 값 변경

- frontend/src/layouts/SideBar.vue
- frontend/src/stores/workspace/useWorkspaceStore.js
- frontend/src/view/dashboard/component/TaskOverview.vue
- frontend/src/view/dashboard/component/WorkspaceTaskOverview.vue
<br>
- 워크스페이스 이름을 제대로 받을 수 있도록 잘못된 로직을 수정했습니다.
- 불필요한 api 요청을 삭제했습니다.
- 대시보드에서 진행 비율을 그릴 때, 소수점 2자리 밑으로 자르도록 수정했습니다. 
<br>
> [Refactor] 사이드바 수정

- frontend/src/stores/user/useUserStore.js
<br>
- userId랑 userName를 못 받아오는 부분 해결 했습니다.
-
<br>
> [Fix] 유저 관련 받아오는 값 오류 해결

- frontend/src/main.js
<br>
- SSE 연결 경로를 수정했습니다.
<br>
> [Refactor] SSE 연결 경로 수정

- cicd/Jenkinsfile-batch
- cicd/k8s-batch.yml
<br>
- 젠킨스 파일을 수정하여 롤링 업데이트와 같이 동작하도록 수정했습니다.
- 크론잡이 하나의 성공한 job만 유지하도록 수정하여 불필요한 파드를 삭제하도록 수정했습니다.
<br>
> [Refactor] batch cicd 수정

- frontend/src/view/board/create/QACreatePage.vue
<br>
- 사용하지 않는 변수가 있어서 build에 실패하는 에러를 해결했습니다.
<br>
> [Fix] 사용하지 않는 변수 제거

- backend/common/src/main/java/minionz/common/note/model/Note.java
<br>
- 누락된 엔터티 속성을 추가해 오류를 수정했습니다.
<br>
> [Fix] 누락된 엔터티 속성 추가

- backend/common/src/main/java/minionz/common/note/model/Note.java
Reverts beyond-sw-camp/be06-fin-MINIONZ-CalIT#475
> Revert "[Fix] 누락된 엔터티 속성 추가"

- frontend/src/stores/chat/useChatMessageStore.js
- frontend/src/view/chat/component/ChatMessage.vue
- frontend/src/view/chat/component/ChatRoomComponent.vue
<br>
- 채팅 파일 중복으로 반환하기에 오류가 생기는 것 같아서 store에서 처리할 수 있도록 수정 했습니다.
-
<br>
> [Refactor] 채팅 파일 중복 반환 수정

- backend/api-server/src/main/java/minionz/apiserver/chat/chat_bot/ChatBotService.java
- backend/api-server/src/main/java/minionz/apiserver/chat/chat_room/ChatRoomService.java
<br>
- 개인 채팅방 생성 시에도 지정한 채팅방 이름으로 생성되게 수정 했습니다.
- 자동화 워크플로우 주소를 이제 localhost가 아닌 배포 된 환경으로 재구성 했습니다.
<br> 
배포 환경에서 구성된 거 확인 될 시에 url 수정 후 환경 변수로 다시 변경 하겠습니다.
> [Fix] 채팅방 생성 이름 변경 수정 및 챗봇 배포 환경 url 변경

- frontend/src/view/scrum/Task/kanban/WorkSpaceTaskKanbanPage.vue
- frontend/src/view/scrum/Task/kanban/component/KanbanCard.vue
- frontend/src/view/scrum/meeting/MeetingDetailPage.vue
- frontend/src/view/scrum/meeting/MeetingListPage.vue
- frontend/src/view/scrum/meeting/component/MeetingCard.vue
<br>
- 정렬되지 않은 칸반을 NO_STATUS, TODO, DONE 순으로 정렬했습니다. 
- 백엔드와 연동되지 않은 라벨을 연결하고, response 에 맞게 라벨을 수정했습니다.
- 잘못된 css를 삭제하여 올바르게 동작하도록 수정했습니다.  
<br>
> [Fix] 태스크 및 이슈 에러 관련 해결

- frontend/src/view/scrum/Task/kanban/component/KanbanCard.vue
<br>
- 잘못된 방식으로 데이터를 호출하는 부분을 수정하여 정상적으로 라벨을 그리도록 구현했습니다.
<br>
> [Fix] 잘못된 데이터 호출 수정

- backend/api-server/src/main/java/minionz/apiserver/chat/chat_bot/ChatBotService.java
- backend/api-server/src/main/resources/application.yml
<br>
- url을 배포 환경 주소로 환경 변수 처리 했습니다.
-
<br> 
푸쉬하고, docker랑 k8s에 config 추가하러 가겠습니다.
> [Fix] 챗봇 N8N url 환경 변수 처리

- frontend/src/view/schedule/monthly/WorkSpaceMonthlyPage.vue
<br>
- 워크스페이스의 monthly 조회 시 workspaceId가 undefined 로 전달되는 문제를 해결하기 위해 route의 param에서 값을 가져오도록 수정했습니다.
<br>
> [Fix] workspaceId undefined 문제 해결

- backend/api-server/src/main/java/minionz/apiserver/scrum/meeting/MeetingService.java
- backend/api-server/src/main/java/minionz/apiserver/scrum/meeting/model/response/ReadMeetingResponse.java
- backend/api-server/src/main/java/minionz/apiserver/scrum/task/TaskController.java
- backend/api-server/src/main/java/minionz/apiserver/scrum/task/TaskService.java
- backend/api-server/src/main/java/minionz/apiserver/scrum/workspace/WorkspaceController.java
- backend/common/src/main/java/minionz/common/scrum/task/repository/TaskRepository.java
- backend/common/src/main/java/minionz/common/scrum/task/repository/TaskRepositoryCustom.java
- backend/common/src/main/java/minionz/common/scrum/task/repository/TaskRepositoryCustomImpl.java
<br>
- 미팅 조회할 때 라벨을 함께 반환하도록 수정했습니다.
- 워크스페이스 별로 태스크를 조회할 때, 해당 메서드가 태스크 컨트롤러에 있으면 권한 문제로 조회가 불가능했습니다. 워크스페이스 컨트롤러로 이동하며 에러를 해결했습니다.
- 워크스페이스 별로 태스크를 조회하는 queryDSL을 구현했습니다. 
<br>
> [Refactor] 

- frontend/src/common/component/Board/QABoardDetail.vue
- frontend/src/stores/scrum/useTaskStore.js
- frontend/src/view/board/detail/QADetailPage.vue
- frontend/src/view/scrum/Task/list/component/ListItem.vue
<br>
- 워크스페이스 별 태스크를 조회하는 api의 url을 수정했습니다.
- qa 게시판 리스트 조회 및 생성과 상세 조회 시 올바른 데이터 바인딩으로 게시판과 관련된 오류들을 수정했습니다.
<br> 
qa 게시글을 등록할 때 파일 업로드 시 form 객체가 제대로 전달이 안됩니다. 추후 수정이 필요합니다.
> [Fix] qa 게시판 에러 수정

- frontend/package.json
- frontend/src/common/component/Editor/QuillEditorMeeting.vue
- frontend/src/view/scrum/meeting/MeetingListPage.vue
- frontend/yarn.lock
#486 
<br>
- 회의록 공동작성에 quillcursor 도입했습니다.
<br>
> [Refactor] 회의록 공동작성 quillcursor 도입 [#486] 

- backend/api-server/src/main/resources/application.yml
#488 
<br>
- redis 설정 관련 yml 파일 수정했습니다.
<br>
> [Refactor] redis 관련 환경변수 설정 변경 [#488]

- backend/api-server/src/main/java/minionz/apiserver/alarm/AlarmService.java
<br>
- 배치 작업 시 전송되는 알림의 데이터 타입을 수정했습니다.
<br>
> [Refactor] batch 실행 시 전송되는 알림 데이터 타입 수정

- backend/api-server/src/main/java/minionz/apiserver/scrum/label/LabelController.java
- backend/api-server/src/main/java/minionz/apiserver/scrum/meeting/MeetingController.java
- backend/api-server/src/main/java/minionz/apiserver/scrum/sprint/SprintController.java
- backend/api-server/src/main/java/minionz/apiserver/scrum/task/TaskController.java
> [Fix] 어노테이션 수정

- frontend/src/stores/scrum/useMeetingStore.js
- frontend/src/stores/scrum/useSprintLabelStore.js
- frontend/src/stores/scrum/useSprintStore.js
- frontend/src/stores/scrum/useTaskLabelStore.js
- frontend/src/stores/scrum/useTaskStore.js
<br>
- api 경로 및 http 메서드를 수정했습니다.
- 유저별 태스크를 상태별로 조회하는 함수를 구현했습니다.
<br>
> [Fix] api 경로 수정 

- frontend/src/stores/board/useQAStore.js
<br>
- store에서 export 누락으로 인한 데이터 호출 오류를 수정했습니다.
<br>
> [Feat] export 누락으로 인한 오류 수정

- frontend/src/view/schedule/monthly/MyMonthlyPage.vue
- frontend/src/view/schedule/monthly/WorkSpaceMonthlyPage.vue
- frontend/src/view/schedule/monthly/component/MonthlyComponent.vue
- frontend/src/view/schedule/weekly/WorkSpaceWeeklyPage.vue
- frontend/src/view/schedule/weekly/component/WeeklyComponent.vue
<br>
- 먼슬리에서 달 이동 시 띄워지는 구성이 작동하지 않는 부분을 수정하였습니다.
- 위클리에서 스프린트를 띄우는 부분을 수정하였습니다. 추후에 UI가 수정될 예정입니다.
<br>
> [Refactor] 먼슬리 날짜 구성 및 전송 수정, 위클리 수정

- frontend/src/stores/scrum/useSprintLabelStore.js
<br>
- 스프린트 조회 및 생성 함수가 반대의 http 메서드를 사용하고 있엇 수정했습니다.
<br>
> [Fix] http 메서드 수정

- backend/api-server/src/main/java/minionz/apiserver/search/SearchService.java
- backend/common/src/main/java/minionz/common/user/UserRepository.java
<br>
- 워크스페이스 내 멤버를 조회할 때, 참여한 멤버만 조회하도록 로직을 수정했습니다.
<br>
> [Refactor] 워크스페이스 내 멤버 조회 로직 수정

- backend/api-server/src/main/java/minionz/apiserver/scrum/sprint/SprintService.java
- backend/api-server/src/main/java/minionz/apiserver/scrum/task/TaskService.java
- backend/api-server/src/main/java/minionz/apiserver/scrum/task/model/response/ReadAllTaskResponse.java
<br>
- 태스크 리스트 조회 시 done_date 컬럼을 추가했습니다.
- null 예외처리를 추가했습니다.
<br>
> [Refactor] 태스크 리스트 조회 기능 수정

- backend/api-server/src/main/java/minionz/apiserver/config/SecurityConfig.java
- backend/api-server/src/main/java/minionz/apiserver/scrum/task/TaskController.java
- backend/api-server/src/main/java/minionz/apiserver/scrum/task/TaskService.java
- backend/api-server/src/main/java/minionz/apiserver/scrum/task/model/request/CreateTaskRequest.java
<br>
- 태스크 조회 시 스프린트의 참여 여부에 따라 권한을 확인하면 너무 잦은 페이지에 권한 없음이 뜨기 때문에, 조회에 한해서 권한을 갖도록 수정했고 이에 따라 워크스페이스 아이디를 매개변수로 전달하도록 수정했습니다.
<br>
> [Refactor] 태스크 조회 권한 변경

- frontend/src/stores/scrum/useSprintStore.js
- frontend/src/view/scrum/create/SprintCreatePage.vue
- frontend/src/view/scrum/list/IssueListPage.vue
- frontend/src/view/scrum/list/SprintListPage.vue
<br>
- 비동기 데이터 로딩 시점에서 발생하는 렌더링 문제를 해결하기 위해 간단한 로딩 표시(span 태그)를 추가했습니다.
- 데이터 로드 중일 때 "로딩 중" 메시지를 표시하여 사용자에게 로딩 상태를 알리도록 구현했습니다.
- 스프린트 생성 시 notyf 알람을 컴포넌트가 아닌 store에서 관리하도록 수정하여 알람 메시지 처리를 일관되게 관리했습니다. 
<br> 
현재는 단순히 로딩 상태를 알리기 위한 기능만 추가되어 있으며, 추후에 스켈레톤 UI를 도입하여 사용자 경험을 향상시키는 것도 고려해 볼 수 있습니다.
> [Feat] 비동기 데이터 로딩 시 로딩 표시 추가 및 알림 처리 로직 개선

- backend/api-server/src/main/java/minionz/apiserver/board/error_comment/ErrorCommentController.java
- backend/api-server/src/main/java/minionz/apiserver/board/qa_comment/QaCommentController.java
- backend/api-server/src/main/java/minionz/apiserver/common/responses/BaseResponseStatus.java
#30 
<br>
- 댓글 관련  api 수정했습니다.
-
<br>
> [Refactor] 댓글 api 수정 [#30]

- backend/api-server/src/main/java/minionz/apiserver/board/qa_board/QaBoardService.java
- backend/api-server/src/main/java/minionz/apiserver/board/qa_board/model/response/CreateQaBoardResponse.java
#30 
<br>
- qa 담당자 response 수정했습니다.
-
<br>
> [refactor] QA 담당자 response 추가

- backend/api-server/src/main/java/minionz/apiserver/scrum/dashboard/DashboardController.java
- backend/api-server/src/main/java/minionz/apiserver/scrum/dashboard/DashboardService.java
- backend/common/src/main/java/minionz/common/scrum/meeting/MeetingRepository.java
- backend/common/src/main/java/minionz/common/scrum/sprint/repository/SprintRepositoryCustom.java
- backend/common/src/main/java/minionz/common/scrum/sprint/repository/SprintRepositoryCustomImpl.java
- backend/common/src/main/java/minionz/common/scrum/task/repository/TaskRepositoryCustomImpl.java
<br>
- 워크스페이스의 대시보드 조회 시 다가오는 미팅의 개수를 8개로 정하여 임박 순으로 보여주도록 수정했습니다.
- queryDSL로 리팩토링하며 잘못 구현된 조건을 수정하여 올바른 값을 가져오도록 수정했습니다. 
<br>
> [Refactor] 워크스페이스 대시보드 조회 기능 수정

- frontend/src/common/component/Board/ErrorBoardList.vue
- frontend/src/stores/scrum/useTaskStore.js
- frontend/src/view/board/detail/ErrorDetailPage.vue
<br>
- 에러 게시판 상세 조회 시 파라미터를 전달하지 않아 undefined가 발생하는 오류를 수정했습니다.
- 나의 칸반 조회의 url을 수정했습니다.
<br>
> [Fix] 에러게시판 param 에러 수정

- frontend/src/common/component/Board/ErrorBoardList.vue
- frontend/src/common/component/RightSide/RightSideIssue.vue
- frontend/src/common/component/RightSide/RightSideParticipants.vue
- frontend/src/layouts/AppHeader.vue
- frontend/src/layouts/component/modal/AlarmModal.vue
- frontend/src/layouts/component/modal/WorkspaceModal.vue
- frontend/src/stores/myspace/useMyDashboardStore.js
- frontend/src/stores/workspace/useWorkspaceDashboardStore.js
- frontend/src/view/schedule/weekly/MyWeeklyPage.vue
- frontend/src/view/schedule/weekly/WorkSpaceWeeklyPage.vue
- frontend/src/view/schedule/weekly/component/WeeklyComponent.vue
- frontend/src/view/scrum/create/SprintCreatePage.vue
- frontend/src/view/scrum/meeting/MeetingCreatePage.vue
- frontend/src/view/scrum/meeting/MeetingListPage.vue
<br>
- 위클리 날짜 전송 값이 수정되었습니다.
- 회의 추가 로직이 변경되었습니다.
- 참여자 추가 부분이 수정되었습니다.
- 회의에서 이슈 추가가 가능합니다.
- 회의 목록에서 발생하는 이슈가 수정되었습니다.
- 에러 보드가 수정되었습니다.
- 앱 헤더에서 null값 shapeFlag 값 조회로 인한 오류를 수정하였습니다.
<br>
> [Refactor] 위클리, 회의, 참여자 추가, 이슈 추가, 에러 보드 상세 수정

- frontend/src/common/component/Board/ErrorBoardList.vue
- frontend/src/common/component/SearchComponent.vue
- frontend/src/stores/workspace/useWorkspaceDashboardStore.js
- frontend/src/view/board/create/ErrorCreatePage.vue
- frontend/src/view/scrum/meeting/MeetingCreatePage.vue
<br>
- 미사용 값들을 주석처리 하였습니다.
<br>
> [Refactor] 미사용 코드 주석 처리

- backend/api-server/src/main/java/minionz/apiserver/alarm/AlarmService.java
<br>
- 자주 끊기는 환경을 수정하기 위해 max 값을 변경 했습니다.
-
<br>
> [Fix] 알람 max 값 변경

- cicd/k8s-backend.yml
<br>
- 쿠버네티스 백엔드 야멜 파일 수정했습니다.
<br>
> [Refactor] backend yml 파일 수정

- backend/api-server/src/main/resources/application.yml
<br>
- application.yml  파일에서 redis_port 환경변수 다시 설정했습니다.
<br>
> [Refactor] backend yml 파일 수정2

- backend/api-server/src/main/resources/application.yml
<br>
- application.yml 파일 redis 부분 설정 변경하였습니다.
<br>
> [Refactor] backend yml 파일 수정3

- frontend/src/view/board/create/ErrorCreatePage.vue
- frontend/src/view/board/list/ErrorListPage.vue
- frontend/src/view/schedule/weekly/MyWeeklyPage.vue
- frontend/src/view/schedule/weekly/WorkSpaceWeeklyPage.vue
<br>
- weeklypage에서 onMount 하지 않는 부분을 수정하였습니다.
-
<br>
> [Refactor] 주간 페이지 onMounted 수정

- frontend/src/view/chat/component/ChatMessage.vue
- frontend/src/view/chat/component/ChatRoomComponent.vue
<br>
- 채팅방을 열었을 때, 위에 원래는 본인의 이름이 되어 있었는데, 채팅방 이름으로 변경했습니다.
- 채팅 상대의 이름 또한 위에 뜰 수 있게 설정. 그룹 채팅방일 경우에 누가 보냈는지를 알 수 없습니다.
<br>
> [Refactor] 채팅 상대 이름 받아오기 및 채팅방 이름 설정

- backend/api-server/src/main/resources/application.yml
<br>
- application.yml 파일 spring 밑에 data 밑에 redis 가 위치하도록 수정했습니다.
<br>
> [Refactor] backend yml 파일 수정4

- frontend/src/view/schedule/weekly/WorkSpaceWeeklyPage.vue
- frontend/src/view/schedule/weekly/component/WeeklyComponent.vue
<br>
- 날짜 변경 시 위클리에 날짜 반영이 되지 않는 오류를 수정하였습니다.
<br>
> [Refactor] 주간 페이지 날짜 변환 수정

- frontend/src/common/component/SearchComponent.vue
- frontend/src/view/board/list/ErrorListPage.vue
- frontend/src/view/schedule/weekly/component/WeeklyComponent.vue
<br>
- 주간 페이지 날짜 변환 수정
- 에러 게시판 수정
<br>
> [Refactor] 주간 페이지 날짜 변환 수정, 에러 게시판 언어별 필터링 수정

- frontend/src/common/component/Board/SprintList.vue
- frontend/src/common/component/SearchComponent.vue
- frontend/src/view/scrum/list/IssueListPage.vue
- frontend/src/view/scrum/list/SprintListPage.vue
- frontend/src/view/scrum/list/component/IssueListComponent.vue
- frontend/src/view/scrum/meeting/MeetingListPage.vue
- frontend/src/view/user/pages/LoginPage.vue
<br>
- 이슈 및 스프린트 조회 시 검색 기능이 없어서 검색 창을 disabled 처리했습니다.
- isLoading을 추가하여 사용자 경험을 향상시켰습니다.
- 리스트에 마우스가 hover 됐을 때, 사용자 경험을 위한 css를 추가했습니다.
<br>
> [Refactor] 사용자 경험을 위한 css 추가 및 isLoading 구현

- frontend/src/view/board/create/QACreatePage.vue
- frontend/src/view/board/list/QAListPage.vue
#30 
<br>
- Qa 생성시 담당자 지정 수정했습니다.
<br>
>  [Refactor] Qa 생성 수정 [#30]

- frontend/src/stores/board/useQAStore.js
- frontend/src/view/board/list/ErrorListPage.vue
- frontend/src/view/board/list/QAListPage.vue
- frontend/src/view/schedule/weekly/component/WeeklyComponent.vue
- frontend/src/view/scrum/Task/component/TaskViewBar.vue
- frontend/src/view/scrum/Task/kanban/MyTaskKanbanPage.vue
- frontend/src/view/scrum/Task/kanban/WorkSpaceTaskKanbanPage.vue
- frontend/src/view/scrum/Task/kanban/component/KanbanColumn.vue
- frontend/src/view/scrum/Task/list/MyTaskListPage.vue
- frontend/src/view/scrum/Task/list/WorkSpaceTaskListPage.vue
- frontend/src/view/scrum/Task/list/component/ListContainer.vue
- frontend/src/view/scrum/Task/list/component/ListItem.vue
<br>
- weekly의 sprint 길이 및 UI 깨짐 수정 완료
- my kanban 수정완료
- error 게시판 필터링 수정 완료
- error, qa 검색 완료
<br>
> [Refactor] weekly 수정 my kanban 수정, error 게시판 필터링 수정

- frontend/src/view/scrum/Task/create/WorkSpaceTaskCreatePage.vue
- frontend/src/view/scrum/create/SprintCreatePage.vue
- frontend/src/view/scrum/detail/SprintDetailPage.vue
<br>
- 라벨을 생성하는 ui가 존재하지 않아 백엔드에서 라벨을 생성하여 가져오도록 로직을 수정했습니다. 
- 스프린트 상세 조회 시 라벨의 key가 맞지 렌더링 되지 않는 문제를 수정했습니다.
<br>
> [Refactor] 라벨 관련 이슈 해결

- frontend/src/common/component/PaginationComponent.vue
- frontend/src/view/board/list/ErrorListPage.vue
- frontend/src/view/schedule/monthly/component/MonthlyComponent.vue
- frontend/src/view/schedule/weekly/MyWeeklyPage.vue
- frontend/src/view/schedule/weekly/component/WeeklyComponent.vue
<br>
- my weekly의 데이터 바인딩을 수정하였습니다.
<br>
> [Refactor] my weekly 수정

- frontend/src/view/chatbot/ChatMessage.vue
- frontend/src/view/scrum/meeting/MeetingCreatePage.vue
<br>
- 회의 생성에 스프린트 추가를 하고, 라벨 선택 사항을 변경 했습니다.
-
<br>
> [Refactor] 회의 생성 스프린트 추가

- frontend/src/common/component/PaginationComponent.vue
- frontend/src/stores/scrum/useMeetingStore.js
- frontend/src/view/scrum/meeting/MeetingListPage.vue
<br>
- 미팅 목록 조회 시 페이지네이션이 되도록 수정했습니다.
<br> 
추후 css 수정이 필요합니다.
> [Fix] 미팅 목록 페이지네이션 수정

- backend/api-server/src/main/java/minionz/apiserver/scrum/issue/IssueService.java
- backend/api-server/src/main/java/minionz/apiserver/scrum/issue/model/response/ReadIssueResponse.java
- backend/api-server/src/main/java/minionz/apiserver/scrum/meeting/MeetingController.java
- backend/api-server/src/main/java/minionz/apiserver/scrum/meeting/MeetingService.java
- backend/api-server/src/main/java/minionz/apiserver/scrum/meeting/model/request/CreateMeetingRequest.java
- backend/common/src/main/java/minionz/common/scrum/meeting/MeetingRepository.java
<br>
- 회의 생성 시 목록 기능을 수정했습니다.
- 회의 리스트 조회 시 정렬을 추가했습니다.
<br>
> [Fix] 회의 목록 조회 기능 수정

- frontend/src/common/component/RightSide/RightSideParticipants.vue
- frontend/src/stores/scrum/useMeetingStore.js
- frontend/src/view/chatbot/ChatMessage.vue
- frontend/src/view/scrum/meeting/MeetingCreatePage.vue
<br>
- 회의 생성 및 리스트 조회 시 에러를 해결했습니다.
<br>
> [Fix] 회의 생성 및 리스트 조회 기능 수정

- frontend/src/view/scrum/Task/list/WorkSpaceTaskListPage.vue
- frontend/src/view/scrum/Task/list/component/ListContainer.vue
<br>
- 워크스페이스 태스크 리스트 조회 시 드래그 앤 드랍 기능이 정상적으로 동작하도록 수정했습니다.
- 스프린트를 선택할 때마다 데이터를 fetch 해오도록 수정했습니다.
<br>
> [Refactor] 워크스페이스 리스트 드래그앤 드랍 기능 수정

- frontend/src/common/component/RightSide/RightSideComponent.vue
- frontend/src/common/component/RightSide/RightSideParticipants.vue
- frontend/src/layouts/AppHeader.vue
- frontend/src/layouts/component/modal/WorkspaceModal.vue
- frontend/src/utils/scheduleDateSettingUtils.js
- frontend/src/utils/timeUtils.js
- frontend/src/view/chat/component/ChatRoomList.vue
- frontend/src/view/dashboard/MyDashBoardPage.vue
- frontend/src/view/dashboard/component/BurndownChart.vue
- frontend/src/view/dashboard/component/PriorityTask.vue
- frontend/src/view/schedule/weekly/component/WeeklyComponent.vue
- frontend/src/view/scrum/create/WorkSpaceCreatePage.vue
- frontend/src/view/scrum/meeting/MeetingCreatePage.vue
- frontend/src/view/scrum/meeting/MeetingListPage.vue
- frontend/src/view/user/UserTemplate.vue
- frontend/src/view/user/component/SocialLogin.vue
- frontend/src/view/user/component/UserButton.vue
- frontend/src/view/user/component/UserInput.vue
- frontend/src/view/user/pages/LoginPage.vue
- frontend/src/view/user/pages/SignupPage.vue
- frontend/src/view/user/pages/SocialRedirectionPage.vue
<br>
- 데이터가 추가되며 UI가 깨지는 부분들과 동작 중 발생하는 에러들을 수정했습니다.
<br>
> [Refactor] UI 깨짐 오류 해결

- frontend/src/utils/timeUtils.js
<br>
- 서버와의 시간차를 줄이기 위해 setHour+9 처리를 하였습니다.
<br>
> [Refactor] 배포환경 시간 수정

- frontend/src/view/user/pages/SocialRedirectionPage.vue
<br>
- 소셜 로그인의 api 연결을 수정했습니다.
<br>
> [Refactor] 소셜 로그인 api 연결 수정

- frontend/src/view/user/pages/SocialRedirectionPage.vue
<br>
- 소셜 로그인 api 연결 수정 잘못된 merge로 인한 revert
<br>
> Revert "[Refactor] 소셜 로그인 api 연결 수정"

- frontend/src/view/user/pages/SocialRedirectionPage.vue
[Refactor] 소셜 로그인 api 연결 수정
<br>
- frontend 개발 내용 develop 브랜치에 병합
<br>
> [Merge] frontend 개발 내용 develop 브랜치에 병합

- frontend/src/view/user/pages/SocialRedirectionPage.vue
<br>
- 프론트 엔드 작업 내용을 브랜치에 병합합니다.
<br>
> [Merge] 프론트엔드 브랜치 병합

- frontend/src/common/component/Editor/QuillEditorMeeting.vue
#7 
<br>
- quillcursor 뺐습니다.
<br>
> [Refactor] quilleditor 수정

- frontend/src/common/component/Editor/QuillEditorMeeting.vue
- frontend/src/view/user/pages/SocialRedirectionPage.vue
#559 
<br>
- 회의록 관련 커서 제거했습니다.
<br>
> [Refactor] 회의록 관련 커서 제거 [#599]

- backend/api-server/src/main/resources/application.yml
<br>
- sse 알람 연결을 위한 설정을 추가했습니다.
<br>
> [Refactor] sse 알람 연결을 위한 설정 추가

- backend/batch/src/main/java/minionz/batch/config/JobDurationListener.java
- backend/batch/src/main/java/minionz/batch/config/MeetingReminderBatchConfig.java
- backend/batch/src/main/java/minionz/batch/config/SprintReminderBatchConfig.java
- backend/batch/src/main/java/minionz/batch/config/TaskReminderBatchConfig.java
<br>
- 배치 실행 시간을 측정하기 위한 코드를 추가했습니다.
<br>
> [Feat] 배치 시간 측정 코드 추가
