beyond-sw-camp/be06-fin-MINIONZ-CalIT

backend/src/main/java/minionz/backend/chat_participation/model/ChatParticipation.java
CHAT_001 - 채팅방 생성 기능 #2
<br>
- 유저와 채팅방 연관 관계인 M:N은 DB에서 표현하기 위해 연결 테이블인 채팅 참여 테이블을 생성하였다. 
- 메세지:채팅참여, 채팅참여:유저, 채팅방:채팅참여 의 관계를 설정 했다. 
<br> 
채팅참여는 id값 빼고는 갖고 있는 속성값이 없기 때문에 수정 사항 없을 거 같습니당.
=> [Feat] CHAT_001 - 채팅 참여 연관 관계 및 엔티티 추가

backend/src/main/java/minionz/backend/common/BaseEntity.java
<br>
- 공통 타임스탬프 관리용 BaseEntity 을 만들어서 createdAt, modifiedAt 값을 extends해서 사용 할 수 있도록 함 
<br> 
extends BaseEntity <- 해서 사용하시면 될 것 같습니당. 삭제 시간 같은 거는 없는 곳이 더 많아서 개인적으로 관리해요 ,, !
=> [Feat] 공통 타임스탬프 관리용 BaseEntity 구현

backend/build.gradle, backend/src/main/java/minionz/backend/config/WebConfig.java, backend/src/main/java/minionz/backend/config/WebSocketConfig.java, backend/src/main/resources/application.yml
#2 
<br>
- WebConfig : 
- cors 설정을 추가해서 클라이언트 도메인에 대한 접근을 허용하도록 했습니다. 
- 허용된 도메인은 `address.domain` 로 환경 변수에서 설정 되게 했습니다. 
-  `GET`, `POST`, `PATCH`, `DELETE` 메서드와 `Authorization`, `Content-Type` 헤더를 지원하도록 했습니다.
- WebSocketConfig: 
- WebSocket과 STOMP 설정을 추가하여 실시간 메시징을 지원하도록 했습니다. 
- `/chat` 엔드포인트를 등록하고, 모든 도메인에서의 접근을 허용합니다.
- 메시지 브로커 설정을 통해 `/sub` 경로로 구독 및 `/pub` 경로로 메시지 전송을 지원합니다.
- application.yml:
- 환경 변수 처리해서 올려뒀습니다. 필요하신 부분은 추가 해 주시면 됩니다.
- build.gradle에 WebSocket이 없어서 추가 해 뒀습니다.
<br> 
`address.domain`  이 부분은 yml에 추후에 추가 할 예정입니다. 현재 올리는 yml 에는 없습니다.
=> [Feat] CORS 및 WebSocket 설정 추가

backend/src/main/java/minionz/backend/chat/chat_participation/model/ChatParticipation.java, backend/src/main/java/minionz/backend/chat/chat_room/model/ChatRoom.java, backend/src/main/java/minionz/backend/chat/message/model/Message.java, backend/src/main/java/minionz/backend/chat/message/model/MessageStatus.java, backend/src/main/java/minionz/backend/chat/message/model/MessageType.java, backend/src/main/java/minionz/backend/config/kafka/KafkaConstants.java, backend/src/main/java/minionz/backend/config/kafka/KafkaConsumerConfig.java, backend/src/main/java/minionz/backend/config/kafka/KafkaProducerConfig.java, backend/src/main/java/minionz/backend/config/web/WebConfig.java, backend/src/main/java/minionz/backend/config/web/WebSocketConfig.java, backend/src/main/java/minionz/backend/user/model/User.java, backend/src/main/resources/application.yml
#2 #20
<br>
- 폴더 구조 변경 했습니다. 
- chat 안에 [ message, chat_room, chat_participation ] 을 넣어서 체계적으로 관리하도록 했습니다.
- config에 kafka 폴더를 만들어서 안에 관련 config 들을 구현 후 넣어놨습니다.
- KafkaConstants: `GROUP_ID` 를 uuid로 관리 하도록 만들었습니다.
- KafkaConsumerConfig: kafka에서 메세지를 가지고 오는 역할을 하는 `consumerFactory` 를 생성하고, `consumer` `kafka`에 필요한 설정들을 추가 했습니다.
- KafkaProducerConfig: `ProducerFactory`와 `KafkaTemplate`을 설정하여 `Kafka`에 메세지를 전송할 준비하는 `Config`라고 생각 해 주시면 됩니다.
- 이해를 위해 실행 순서 주석을 달아뒀으니 순서 참고 하시면 됩니다.
<br> 
`application.yml` 안에 `kafka server` 를 적어야 하는 칸을 추가 해 뒀습니다. 해당 관련 된 것들은 discord에 올려놓겠습니다. 필요하신 분들은 각자 `local.yml`에 추가해서 쓰시면 될 것 같습니다.!
=> [Feat] CHAT_001 - kafka Config 추가 [#2, #20]

backend/src/main/java/minionz/backend/common/responses/BaseResponseStatus.java, backend/src/main/java/minionz/backend/scrum/label/LabelService.java, backend/src/main/java/minionz/backend/scrum/sprint/SprintController.java, backend/src/main/java/minionz/backend/scrum/sprint/SprintRepository.java, backend/src/main/java/minionz/backend/scrum/sprint/SprintService.java, backend/src/main/java/minionz/backend/scrum/sprint/model/request/CreateSprintRequest.java, backend/src/main/java/minionz/backend/scrum/sprint_participation/SprintParticipationRepository.java, backend/src/main/java/minionz/backend/scrum/workspace/WorkspaceController.java, backend/src/main/java/minionz/backend/scrum/workspace_participation/WorkspaceParticipationRepository.java
#86 
<br>
- 워크스페이스에서 스프린트를 생성하는 기능을 구현했습니다.
- 스프린트를 생성하면 스프린트 참여 테이블에 참여자들이 추가되도록 구현했습니다.
- 스프린트 생성 시 전달받은 스프린트 라벨들을 스프린트 라벨 선택 테이블에 추가되도록 구현했습니다.
- 스프린트를 생성하는 유저가 워크스페이스 내에 존재하는 유저인지에 대한 유효성 검증을 마쳤습니다.
<br> 
- 알람기능 구현 후 스프린트에 참여된 유저에게 알람을 보내도록 추가 구현이 필요합니다.
- 추후 요청 데이터로 전달받은 스프린트 라벨이 실제 워크스페이스 내 존재하는 라벨인지에 대한 유효성 검증이 필요합니다.
close #86
=> [Feat] SPRINT_001 - 스프린트 생성 기능 구현 [#86]

backend/build.gradle, backend/src/main/java/minionz/backend/chat/chat_participation/ChatParticipationRepository.java, backend/src/main/java/minionz/backend/chat/chat_participation/model/ChatParticipation.java, backend/src/main/java/minionz/backend/chat/chat_room/ChatRoomController.java, backend/src/main/java/minionz/backend/chat/chat_room/ChatRoomRepository.java, backend/src/main/java/minionz/backend/chat/chat_room/ChatRoomService.java, backend/src/main/java/minionz/backend/chat/chat_room/model/ChatRoom.java, backend/src/main/java/minionz/backend/chat/chat_room/model/request/CreatePersonalChatRoomRequest.java, backend/src/main/java/minionz/backend/chat/chat_room/model/response/CreatePersonalChatRoomResponse.java, backend/src/main/java/minionz/backend/chat/chat_room/model/response/ReadChatRoomResponse.java, backend/src/main/java/minionz/backend/chat/message/MessageController.java, backend/src/main/java/minionz/backend/chat/message/MessageRepository.java, backend/src/main/java/minionz/backend/chat/message/MessageService.java, backend/src/main/java/minionz/backend/chat/message/model/Message.java, backend/src/main/java/minionz/backend/chat/message/model/request/MessageRequest.java, backend/src/main/java/minionz/backend/chat/message/model/request/PrivateMessageRequest.java, backend/src/main/java/minionz/backend/chat/message/model/response/MessageResponse.java, backend/src/main/java/minionz/backend/chat/message/model/response/PrivateMessageResponse.java, backend/src/main/java/minionz/backend/common/responses/BaseResponseStatus.java, backend/src/main/java/minionz/backend/config/kafka/KafkaConstants.java, backend/src/main/java/minionz/backend/config/kafka/KafkaConsumerConfig.java, backend/src/main/java/minionz/backend/config/kafka/KafkaProducerConfig.java
[#2, #11, #20] 
<br>
- Build 부분에 json 데이터를 처리하기 위해 jackson 추가 했습니다. 
- baseResponse에 채팅 관련 상태 6000번으로 추가 했습니다.
- 채팅, 채팅방, 채팅참여 관련 엔티티 속성 추가 했습니다.
- kafka 그룹id를 원래 uuid로 설정되게 받아 왔었는데 kafka consumerconfig가 제대로 읽히지 않는 오류로 그룹 id를 지정하는 형태로 변경 했습니다. 이 부분은 전달사항 참고 하시면 추가적으로 적어두겠습니다. 
- <String, MessageRequst> 형태와 , <String, String> 형태 두 가지 형태로 받아왔었는데 producerConfig와, ConsumerConfig 둘 다 팩토리 생성에서 문제가 생기는 것 같아 <String, MessageRequst> 로 받아오는 형식을 아예 삭제 했습니다.
- kafka 메세지 전송 및 토픽에 메세지 내용이 저장 되는 것을 확인했습니다. 현재 그룹 채팅까지 구현했고, 개인 채팅은 이후에 구현 예정입니다.
<br> 
application.yml에 그룹 아이디를 지정 해 주시면 됩니다. 지정 관련은 discord에 올려두도록 하겠습니다. 현재 kafka 메세지 보낼 때 파일 형식은 주석 처리 했습니다. 이는 s3를 통해서 링크를 받아오는 형식으로 수정 예정입니다.
=> [Feat] CHAT_001,003,005 그룹 채팅 메세지 보내기 및 채팅방 생성 [#2, #11, #20] 

backend/src/main/java/minionz/backend/common/responses/BaseResponseStatus.java, backend/src/main/java/minionz/backend/scrum/sprint/SprintController.java, backend/src/main/java/minionz/backend/scrum/sprint/SprintService.java, backend/src/main/java/minionz/backend/scrum/sprint/model/request/UpdateSprintStatusRequest.java, backend/src/main/java/minionz/backend/scrum/task/TaskController.java, backend/src/main/java/minionz/backend/scrum/task/TaskService.java, backend/src/main/java/minionz/backend/scrum/task/model/request/UpdateTaskStatusRequest.java
#100 , #90 
<br>
- 태스크 상태 변경 기능을 구현했습니다.
- 스프린트 상태 변경 기능을 구현했습니다.
- 존재하지 않은 스프린트 및 태스크의 상태를 변경하려고 할 때는 예외처리 했습니다.
- 이전 상태와 동일한 상태로 변경할 때는 예외처리를 했습니다.
- 상태를 DONE으로 변경하면, done_date에 현재 시간이 들어가도록 구현했습니다.
- DONE에서 DONE이 아닌 상태로 변경되면, done_date는 삭제되도록 구현했습니다.
- 스프린트 상태를 DONE으로 변경하면, 스프린트에 속해있는 모든 태스크의 상태를 DONE으로 변경하도록 구현했습니다.
<br> 
close #90 
close #100
=> [Feat] SPRINT_005, TASK_005 - 스프린트 및 태스크 상태 변경 기능 구현 [#100, #90]

backend/src/main/java/minionz/backend/chat/message/MessageController.java, backend/src/main/java/minionz/backend/chat/message/MessageService.java, backend/src/main/java/minionz/backend/chat/message/model/request/MessageRequest.java
#20,#150
<br>
- 전에는 메세지를 전송하고 파일 형식을 남겨둔 채 구현을 했었습니다.
- 파일을 받는 /sendFile api를 따로 구현하고, service는 일반 메세지를 받는 것과 병합했습니다.
- 파일을 받았을 때 kafka로 전송하게 되면 바이너리형식으로 변환해서 쪼개서 관리하는 것 때문에 비효율적이라고 판단 했습니다.
- s3에 저장해서 url을 response로 전달해주는 식으로 구현 했습니다.
<br> 
close #150 
close #20
=> [Feat] CHAT_005,011 - 메세지 및 파일 전송 구현 [#20,#150]

backend/src/main/java/minionz/backend/scrum/task/TaskController.java, backend/src/main/java/minionz/backend/scrum/task/TaskRepository.java, backend/src/main/java/minionz/backend/scrum/task/TaskService.java, backend/src/main/java/minionz/backend/scrum/task/model/response/ReadAllTaskResponse.java, backend/src/main/java/minionz/backend/scrum/workspace/WorkspaceController.java
#102 , #104 
<br>
- 워크스페이스 내의 스프린트 별 칸반조회 기능을 구현했습니다.
- 로그인 한 유저의 모든 워크스페이스에 대한 칸반조회 기능을 구현했습니다.
- 나의 칸반에서는, 스프린트의 마감일이 현재 시점보다 이후인 스프린트에 대해서만 태스크를 조회하도록 구현했습니다.
- 이전에 구현했던 스프린트 리스트 목록 조회 기능을 수정하여 워크스페이스 칸반 조회와 함께 사용할 수 있도록 수정했습니다.
<br> 
close #102 
close #104
=> [Feat] KANBAN_001, KANBAN_002 - 칸반 조회 기능 구현 [#102, #104]

backend/src/main/java/minionz/backend/chat/chat_room/ChatRoomService.java, backend/src/main/java/minionz/backend/chat/message/MessageService.java
[#2,#20,#22]
<br>
- 채팅방을 생성 했을 때 구현 한 순서가 채팅 이름을 설정하고, 초대 할 사람을 선정했었습니다.
- 선정 했을 때 채팅방 참가자들에 초대를 한 본인을 포함하고 있지 않아 포함하도록 설정 했습니다.
- 메세지를 보낼 때 response 응답 값으로 해당 방 참가자들에 대해서 받아오도록 해놨습니다. 
- 원래는 userid를 통해 받아왔다면 chatRoomId를 통해서 받아오게 하여 해당 방에 참가하고 있는 사람들까지 응답할 수 있도록 설정 했습니다.
<br> 
close 했던 이슈들이라 open 이후에 다시 닫았습니다.
=> [Fix] CHAT_001,005,006 - 채팅방에 본인 id 추가 [#2,#20,#22]

backend/src/main/java/minionz/backend/chat/chat_room/ChatRoomService.java, backend/src/main/java/minionz/backend/chat/message/MessageRepository.java, backend/src/main/java/minionz/backend/chat/message/MessageService.java
#11 
<br>
- 조회를 할 때 읽지 않은 메세지 값이 null이라 받아오지 못 하는 오류를 발견했습니다.
- 실제 데이터 값을 넣어서 테스트 할 때 생긴 오류라 message를 보낼 때는 무조건 UNREAD로 설정되게 했습니다.
- 추후에 어떤식으로 READ로 바뀌게 할지는 리팩토링하겠습니다.
- 최신 메세지를 받아올 때 제대로 값을 받아오지 않는 오류를 발견 했습니다.
- repository에서 JPQL 쿼리를 변경하여 제대로 된 값을 불러올 수 있도록 수정했습니다.
- 최신 메세지는 createAt를 기준으로 정렬되게 하여 가장 최신의 값 한 개만 받아오도록 했습니다.
<br> 
없습니다.
=> [Fix] CHAT_003 - 읽지 않은 메세지, 최신 메세지 받아오는 값 수정 [#11]

backend/src/main/java/minionz/backend/common/responses/BaseResponseStatus.java, backend/src/main/java/minionz/backend/scrum/issue/IssueRepository.java, backend/src/main/java/minionz/backend/scrum/meeting/MeetingRepository.java, backend/src/main/java/minionz/backend/scrum/schedule/ScheduleController.java, backend/src/main/java/minionz/backend/scrum/schedule/ScheduleService.java, backend/src/main/java/minionz/backend/scrum/schedule/response/IssueResponse.java, backend/src/main/java/minionz/backend/scrum/schedule/response/ReadWeeklyResponse.java, backend/src/main/java/minionz/backend/scrum/schedule/response/TaskResponse.java, backend/src/main/java/minionz/backend/scrum/sprint/SprintRepository.java, backend/src/main/java/minionz/backend/scrum/task/TaskRepository.java
#106 #108 
<br>
- 워크스페이스의 주별 캘린더 조회 기능을 구현했습니다.
- 로그인 한 유저의 주별 캘린더 조회 기능을 구현했습니다.
- 해당 주가 시작일과 마감일 사이에 포함된 회의와 스프린트, 다가오는 이슈와 태스크를 마감 임박순으로 3개씩 조회하는 기능입니다.
<br> 
close #106 
close #108
=> [Feat] SCHEDULE_002, SCHEDULE_004 - 워크스페이스 주별 캘린더 조회 기능 및 개인 주별 캘린더 조회 기능 구현 [#106, #108]

backend/src/main/java/minionz/backend/scrum/dashboard/DashboardController.java, backend/src/main/java/minionz/backend/scrum/dashboard/DashboardService.java, backend/src/main/java/minionz/backend/scrum/dashboard/model/response/MyProgressResponse.java, backend/src/main/java/minionz/backend/scrum/dashboard/model/response/ReadMyDashboardResponse.java, backend/src/main/java/minionz/backend/scrum/dashboard/model/response/ReadWorkspaceDashboardResponse.java, backend/src/main/java/minionz/backend/scrum/dashboard/model/response/UpcomingMyMeetingResponse.java, backend/src/main/java/minionz/backend/scrum/dashboard/model/response/WorkspaceProgressResponse.java, backend/src/main/java/minionz/backend/scrum/issue/IssueRepository.java, backend/src/main/java/minionz/backend/scrum/sprint/SprintRepository.java, backend/src/main/java/minionz/backend/scrum/task/TaskRepository.java
#109 
<br>
- 번다운 차트를 제외한 워크스페이스의 대시보드 조회 기능을 구현했습니다.
- progress의 sprint count는 마감일이 끝나지 않은 sprint의 개수를 반환합니다.
- progress의 task count는 sprint 마감일이 끝나지 않은 task의 개수를 반환합니다.
- upcoming meetings는 앞으로 2주동안 진행될 회의들에 대해 반환합니다.
<br> 
- 번다운 차트를 구현하여 워크스페이스 대시보드 조회 기능 구현을 완료할 예정입니다.
=> [Feat] DASHBOARD_001 - 워크스페이스 대시보드 조회 기능 구현 [#109]

backend/src/main/java/minionz/backend/chat/message/MessageController.java
#20 , #22 
<br>
- WebSocket으로 파일을 주고 받을 수 있을 줄 알았는데 안 된다는 것을 확인 했습니다.
- 기존 구현 방식대로 메세지는 WebSocket을 써서 받을 수 있게 하고,  파일은 multipart/form-data 으로 처리하도록 해야 하기에 REST API로 처리하도록 변경 했습니다.
<br> 
원래는 response로 파일에 대한 정보까지 보낼 수 있도록 했는데, 이 부분은 채팅내역 조회에서 join 해서 값을 가지고 오도록 구현 해 두겠습니다.
=> [Fix] CHAT_005,006 - 파일 전송 환경 변경 [#20, #22]

backend/build.gradle, backend/src/main/java/minionz/backend/config/web/WebSocketConfig.java
#20 #22 
<br>
- amazon s3 오타 이름 변경했습니다.
- 프론트와 백엔드 연결 과정에서 cors 에러로 인해 모든 도메인에서 접근 가능하도록 허용 해 줬습니다.
<br> 
없습니다.
=> [Fix] CHAT_005,006 - 모든 도메인 접근 허용 [#20, #22]

backend/src/main/java/minionz/backend/chat/chat_room/model/response/ReadMessageResponse.java, backend/src/main/java/minionz/backend/chat/message/MessageController.java, backend/src/main/java/minionz/backend/chat/message/MessageRepository.java, backend/src/main/java/minionz/backend/chat/message/MessageService.java, backend/src/main/java/minionz/backend/common/responses/BaseResponseStatus.java
#25
<br>
- baseResponse에 채팅 내역 조회에 대한 상태 코드들을 추가 했습니다.
- 로그인 한 유저가 선택한 채팅방에 대한 채팅 내역을 받아오도록 했습니다.
<br> 
close #25
=> [Feat] CHAT_007 - 채팅 내역 조회 기능 [#25]

backend/src/main/java/minionz/backend/chat/chat_participation/ChatParticipationRepository.java, backend/src/main/java/minionz/backend/chat/chat_room/model/response/ReadMessageResponse.java, backend/src/main/java/minionz/backend/chat/message/MessageController.java, backend/src/main/java/minionz/backend/chat/message/MessageRepository.java, backend/src/main/java/minionz/backend/chat/message/MessageService.java, backend/src/main/java/minionz/backend/chat/message/model/request/FileInfo.java, backend/src/main/java/minionz/backend/chat/message/model/request/SendMessageRequest.java, backend/src/main/java/minionz/backend/chat/message/model/request/UpdateMessageRequest.java
#26 
<br>
- messageRequest 부분에서 한 번에 처리 하려다가 send와 update로 받는 값이 많이 다르기에 통합하지 않고 구분했습니다.
- 구분하는 과정에서 send 부분을 rename해서  MessageRequest -> SendMessageRequest 로 변경 했습니다.
- 채팅 내역을 조회하는 과정에서 file과 message 부분을 같이 응답 해 주고 있었습니다.
- 프론트에서 페이지 불러올 때 필터링 과정을 생각 해 리스트 형식으로 반환이 필요함을 요청 받았습니다.
- fileInfo를 만들어 그 안에서 file에 대한 내용들을 관리하도록 변경 했습니다.
- 채팅을 수정하는 기능을 구현 했습니다.
<br> 
close #26
=> [Feat] CHAT_008 - 채팅 수정 기능 구현 [#26]

backend/src/main/java/minionz/backend/chat/chat_room/ChatRoomController.java, backend/src/main/java/minionz/backend/chat/chat_room/ChatRoomService.java, backend/src/main/java/minionz/backend/chat/chat_room/model/response/ReadChatRoomResponse.java, backend/src/main/java/minionz/backend/chat/message/MessageController.java, backend/src/main/java/minionz/backend/chat/message/MessageRepository.java, backend/src/main/java/minionz/backend/chat/message/MessageService.java, backend/src/main/java/minionz/backend/common/responses/BaseResponseStatus.java
#2 , #27 
<br>
- 채팅 삭제 기능을 구현 했습니다. 
- 물리적으로 삭제하지 않고, 논리적으로 삭제하게 했습니다.  삭제 여부를 나타내는 deletedAt 를 사용하여 데이터가 삭제 되었음을 표시 했습니다.
- 이 과정에서 채팅 내역을 불러올 때 삭제 내역까지 불러오지 않게 deletedAt의 null 인 채팅 내역만 받아올 수 있도록 이 부분을 수정 했습니다.
- 채팅방 내역을 받아올 때 채팅방이 워크스페이스 내에 존재함을 인지하고 URL 주소를 변경하게 됐습니다. 
-  채팅방 조회를 할 때 workspaceId를 response값으로도 받을 수 있게 수정 했습니다.
- 채팅 삭제 관련 부분에 BaseResponse 상태를 추가 했습니다.
<br> 
close #27
=> [Feat] CHAT_001,009 - 채팅 삭제 기능 구현 및 채팅방 생성 수정 [#2, #27]

backend/src/main/java/minionz/backend/chat/chat_participation/ChatParticipationRepository.java, backend/src/main/java/minionz/backend/chat/chat_room/ChatRoomController.java, backend/src/main/java/minionz/backend/chat/chat_room/ChatRoomService.java, backend/src/main/java/minionz/backend/chat/chat_room/model/request/UpdateChatRoomRequest.java, backend/src/main/java/minionz/backend/common/responses/BaseResponseStatus.java
#18 
<br>
- 채팅방 이름을 수정할 수 있게 구현 했습니다.
- 해당 채팅방이 존재하는지 확인 하고, 채팅방에 참가 중인 유저인지 확인 후에 변경할 수 있도록 구현 했습니다. 
- 채팅방 관련 상태를 추가 했습니다. 추후에 더 추가 될 예정입니다.
<br> 
close #18 
전체적인 채팅방 이름이 변경 돼서 채팅방을 만든 사람만 변경을 해야할지, 변경에는 자유롭게 할지 고민 중입니다. 의견 있으신 분들은 말씀 해 주시면 감사합니다.
=> [Feat] CHAT_004 - 채팅방 수정 기능 구현 [#18]

backend/src/main/java/minionz/backend/chat/chat_participation/ChatParticipationRepository.java, backend/src/main/java/minionz/backend/chat/chat_participation/model/ChatParticipation.java, backend/src/main/java/minionz/backend/chat/chat_room/ChatRoomController.java, backend/src/main/java/minionz/backend/chat/chat_room/ChatRoomService.java, backend/src/main/java/minionz/backend/common/responses/BaseResponseStatus.java
#8
<br>
- 채팅방 나가기 기능을 구현 했습니다.
- 채팅방을 나가게 되면 해당 채팅방이 삭제 되지 않고, 유지되며 나간 해당 사용자만 채팅방을 조회 했을 때 뜨지 않게 했습니다.
- 채팅참여 엔티티에 isActive 라는 사용자가 참여 중인 상태를 볼 수 있게 추가하였습니다.
- 채팅방을 생성 했을 때 자동으로 사용자들은 true라는 값을 갖게 되고, 채팅방을 조회 할 때  isActive가 true인 방만 (참여 중인) 나오도록 했습니다.
- 채팅방 나가기를 눌렀을 시에 isActive가 false으로 바뀌며, 조회가 불가능하게 해 뒀습니다.
- baseResponse 상태값에 채팅방 나가기에 대한 코드들을 추가 해 뒀습니다.
<br> 
close #8
=> [Feat] CHAT_002 - 채팅방 나가기 기능 구현 [#8]

backend/src/main/java/minionz/backend/chat/message/MessageController.java, backend/src/main/java/minionz/backend/chat/message/MessageRepository.java, backend/src/main/java/minionz/backend/chat/message/MessageService.java, backend/src/main/java/minionz/backend/common/responses/BaseResponseStatus.java
#181 
<br>
- 메세지를 전송하면 기본적으로 UNREAD 처리되게 해 두었습니다.
- 채팅방에 들어가기 전까지는 채팅방을 조회 할 때 unreadMessages에 개수가 쌓이고 있었는데, 해당 api를 호출하게 되면 unread의 메세지들의 상태가 전부 read로 변하도록 했습니다.
- 메세지 상태 값 변경에 대한 response status도 추가 해 뒀습니다.
<br> 
close #181
=> [Feat] CHAT_012 - 메세지 상태 값 변경 기능 [#181]

backend/src/main/java/minionz/backend/chat/chat_room/ChatRoomController.java, backend/src/main/java/minionz/backend/chat/chat_room/ChatRoomRepository.java, backend/src/main/java/minionz/backend/chat/chat_room/ChatRoomService.java, backend/src/main/java/minionz/backend/chat/chat_room/model/request/SearchChatRoomRequest.java, backend/src/main/java/minionz/backend/chat/chat_room/model/response/SearchChatRoomResponse.java, backend/src/main/java/minionz/backend/common/responses/BaseResponseStatus.java
#31 
<br>
- 채팅방 내에서 검색 할 수 있는 기능을 구현 했습니다.
- 채팅방을 검색 할 때 마지막 메세지가 파일이면 메세지를 불러오지 못하는 오류를 발견 했습니다.
- url을 불러올까 고민하다 결국 마지막 메세지가 파일 형식이라면,  "파일이 전송되었습니다." 라는 값을 마지막 메세지에 넣도록 설정 했습니다.
- 채팅방 검색에 대한 상태 값을 추가 했습니다.
<br> 
close #31
=> [Feat] CHAT_010 - 채팅 대상 검색 기능 구현 [#31]

frontend/src/layouts/component/WorkSpaceMenu.vue, frontend/src/router/index.js, frontend/src/static/errorListData.js, frontend/src/view/board/create/ErrorCreate.vue, frontend/src/view/board/detail/ErrorDetail.vue, frontend/src/view/board/list/ErrorList.vue
#62 #63 #64
<br>
- error 게시판에 대한 리스트 페이지 ui 마크업을 완성했습니다. 테이블 형태로 구현 됐으며 현재 더미 데이터가 들어가 있습니다.
- error 게시판에 대한 상세 조회 페이지 ui 마크업을 완성했습니다.
- error 게시판에 대한 생성 페이지 ui 마크업을 완성했습니다. quill을 이용한 게시글의 속성과 글이 추가 가능합니다.
<br> 
댓글 구현 미완료 입니다.
=> [Feat] FE_ERR_BOARD001,002,003 Error create, list, detail 페이지

backend/src/main/java/minionz/backend/chat/chat_room/ChatRoomService.java, backend/src/main/java/minionz/backend/chat/message/MessageController.java, backend/src/main/java/minionz/backend/chat/message/model/request/SendMessageRequest.java, backend/src/main/java/minionz/backend/config/SecurityConfig.java, backend/src/main/java/minionz/backend/config/web/WebConfig.java
#11 , #20 
<br>
- 채팅을 전송할 때 customUserDetails 로 userId를 받아오게 했었는데 현재 메세지 테스트를 해 보니 request 안에 id,name을 넣어주는 게 다른 변수가 일어나지 않아 좋다고 판단 되어 변경하게 되었습니다.
- cors 처리를 할 때 SecurityConfig와 WebConfig에서 겹치는 것을 발견하게 되었습니다.
-  cors처리는 WebConfig에서만 하는 것이 적절하다고 생각 되어 SecurityConfig 내용을 없애고 합치게 되었습니다.
- 이 과정에서 허용할 주소를 배열(domains)으로 받아 환경변수 처리를 해 뒀으며 yml 파일에 추가하면 허용할 주소가 유동적으로 변경되기에 이 방법이 더 적절하다고 판단 되어 변경 해 두었습니다.
<br> 
discord 안에 있는 pr 자료방에 domains에 넣어둘 값들을 추가 해 뒀습니다. yml 파일에 그대로 넣어주시면 됩니다.
=> [Refactor] CHAT_003,005 - 메세지 전송 DTO 변경 및 cors 처리 [#11, #20]

backend/src/main/java/minionz/backend/chat/message/MessageService.java, backend/src/main/java/minionz/backend/config/kafka/KafkaConstants.java, backend/src/main/java/minionz/backend/config/kafka/KafkaConsumerConfig.java, backend/src/main/java/minionz/backend/config/kafka/KafkaProducerConfig.java, backend/src/main/resources/application.yml
<br>
- 원래 그룹 아이디를 지정 해 줘서 받아오고 있었는데, k8s에 배포를 하게 되면서 동시 배포에서 충돌을 방지하기 위해 uuid를 그룹 id로 받아오게 했습니다.
- kafka consumer에서 메서드 이름을 맞춰줘야 제대로 동작하는 오류를 발견 했습니다.
- 메서드 이름을 변경하고, uuid를 설정해 주는 클래스를 따로 파 받아오게 했습니다.
- application.yml 파일에서 그룹 아이디 관련 된 것을 삭제 해 줬습니다.
<br> 
없습니다....!
=> [Feat] ETC_003 - KAFKA 그룹 아이디 및 설정 변경

backend/src/main/java/minionz/backend/common/responses/BaseResponseStatus.java, backend/src/main/java/minionz/backend/scrum/issue/IssueController.java, backend/src/main/java/minionz/backend/scrum/issue/IssueRepository.java, backend/src/main/java/minionz/backend/scrum/issue/IssueService.java, backend/src/main/java/minionz/backend/scrum/issue/model/Issue.java, backend/src/main/java/minionz/backend/scrum/issue/model/request/CreateIssueRequest.java, backend/src/main/java/minionz/backend/scrum/issue/model/response/ReadIssueResponse.java
#144 #259 #260 
<br>
- 프론트와 상의하여 이슈 생성할 때 받는 값을 수정 했습니다.
- 단일 조회 및 리스트 조회 부분을 구현 했습니다.
- 이슈는 워크스페이스 내에 생성 되며, workspaceId를 받아 그 워크스페이스내에 있는 이슈 리스트를 조회하거나, 단일 조회를 할 수 있도록 구성했고, api 명세서를 추가 해놨습니다.
<br> 
리뷰어와, 할당자의 역할이 List로 구현 되어야 하는데 생성할 때 Entity안에 List를 넣을 수 없음을 인지 하고 일단은 단일만 넣게 해뒀습니다. 이 문제는 리뷰어와 할당자의 Entity를 만들지 팀원과 상의 후 변경 하겠습니다.
잠깐 테스트 할 때는 권한 설정을 꺼두고 했습니다. 되는 것을 확인 후 올립니다.
close #260 
close #259
=> [Feat] ISSUE_001,002,003 - 이슈 생성 수정 및 단일 조회, 리스트 조회 구현 [#144, #259, #260]

frontend/src/view/schedule/monthly/component/MonthlyComponent.vue, frontend/src/view/schedule/weekly/MyWeeklyPage.vue, frontend/src/view/schedule/weekly/WorkSpaceWeeklyPage.vue, frontend/src/view/schedule/weekly/component/WeeklyIssues.vue, frontend/src/view/schedule/weekly/component/WeeklyTasks.vue
<br>
- 사용하지 않는 변수를 제거했습니다.
- 중복되는 p 태그를 삭제했습니다.
-  워크스페이스 및 마이스페이스에서 위클리 캘린더 조회 시, 프롭스를 전달하지 않아서 데이터를 받지 못하는 문제를 해결했습니다. 
-  바인딩되는 변수를 수정하여 비동기 처리가 안정적이도록 수정했습니다. 
<br>
=> [Fix] 캘린더 위클리 조회 오류 수정

backend/api-server/src/main/java/minionz/apiserver/chat/chat_room/model/response/FileInfoResponse.java, backend/api-server/src/main/java/minionz/apiserver/chat/message/MessageController.java, backend/api-server/src/main/java/minionz/apiserver/chat/message/MessageRepository.java, backend/api-server/src/main/java/minionz/apiserver/chat/message/MessageService.java, backend/api-server/src/main/java/minionz/apiserver/common/responses/BaseResponseStatus.java
#25 
<br>
- 채팅방 내용 조회에서 메세지 타입을 file로 해서 파일과 메세지를 구분 했는데, 무한 스크롤 처리를 하면서 메세지를 올려야 파일 목록 또한 받아오는 것을 발견했습니다.
- 이를 개선하기 위해, 파일 내역 조회 기능을 아예 구현하여 별도로 처리되게 설정 했습니다.
<br>
=> [Feat] CHAT_007 - 채팅방 별 파일 내역 조회 기능 구현 [#25]

backend/api-server/src/main/java/minionz/apiserver/chat/chat_bot/ChatBotController.java, backend/api-server/src/main/java/minionz/apiserver/chat/chat_bot/ChatBotService.java, backend/api-server/src/main/java/minionz/apiserver/chat/chat_bot/model/request/ChatBotRequest.java, backend/api-server/src/main/java/minionz/apiserver/common/responses/BaseResponseStatus.java, backend/api-server/src/main/java/minionz/apiserver/config/web/WebSocketConfig.java, backend/common/src/main/java/minionz/common/chat/chat_bot/model/ChatBot.java, backend/common/src/main/java/minionz/common/user/model/User.java
#371 
<br>
- 사용자가 챗봇에게 메세지를 보내는 것은 WebSocket STOMP를 활용하였습니다.
- 이 메세지를 POST 형태로 N8N에 보내주고, N8N에서 WebHook을 실행시켜 자동화 워크플로우를 실행 시킵니다.
- 이 워크플로우 안에는 회의록 요약 및 회의 자료 추천 기능들이 있습니다. 이 기능을 마치고, POST 형태로 서버에 응답을 주면, 이 응답을 사용자에게 다시 WebSocket STOMP를 활용하여 구독 된 사용자에게 전송하도록 구현했습니다. 
- 챗봇과 사용자의 연관 관계를 1:1로 재수정 하였습니다. 
- 챗봇 상태 코드들을 추가 하였으며, WebSocketConfig에 CHATBOT 부분 또한 추가 해 두었습니다.
<br> 
close #371
=> [Feat] CHATBOT_001 - 챗봇 Ai 연결 기능 구현 [#371]

backend/api-server/src/main/java/minionz/apiserver/config/SecurityConfig.java, backend/api-server/src/main/java/minionz/apiserver/user/model/CustomSecurityUserDetails.java
<br>
- 사용자가 참여하고 있는 스크럼 내역이 많을 때, 토큰의 role의 길이가 너무 길어져 토큰의 헤더가 너무 커져서 502 에러가 발생합니다. 토큰의 변수명의 길이를 대폭 줄여 수정했습니다. 
- 현재 사용하지 않는 미팅 참여 권한은 토큰 생성 시 참여 테이블에 추가하지 않도록 수정했습니다.
<br> 
여전히 참여 내역이 많을 때는 문제가 발생할 수 있습니다.
=> [Fix] 토큰의 role 생성 수정

frontend/src/stores/myspace/useMyDashboardStore.js, frontend/src/stores/scrum/useIssueStore.js, frontend/src/stores/scrum/useMeetingStore.js, frontend/src/stores/scrum/useSprintLabelStore.js, frontend/src/stores/scrum/useSprintStore.js, frontend/src/stores/scrum/useTaskLabelStore.js, frontend/src/stores/scrum/useTaskStore.js, frontend/src/stores/workspace/useWorkspaceDashboardStore.js, frontend/src/stores/workspace/useWorkspaceStore.js, frontend/src/view/scrum/Task/component/TaskViewBar.vue, frontend/src/view/scrum/Task/create/WorkSpaceTaskCreatePage.vue, frontend/src/view/scrum/detail/TaskDetailPage.vue
<br>
- api 요청에서 받은 응답에 따른 예외처리를 했습니다. 특히 자주 발생하는 403 forbidden 상태와 상태코드가 200이더라도 예외처리 된 값일 경우가 있으므로 해당 상황을 모두 알람으로 띄우도록 수정했습니다.
- 태스크 생성 시 백엔드에서 요구하는 타입과 프론트에서 요청 보내는 타입이 맞지 않아 400 에러가 발생했습니다. 필요한 값으로 매핑하여 전달하도록 수정했습니다. 
- 태스크 조회 시 스프린트의 참여 여부에 따라 권한을 확인하면 너무 잦은 페이지에 권한 없음이 뜨기 때문에, 조회에 한해서 권한을 갖도록 수정했고 이에 따라 워크스페이스 아이디를 매개변수로 전달하도록 수정했습니다.
<br> 
최대한 다양한 상황을 테스트하고 보내나, 혹시 빠진 부분이 있을 수도 있습니다. 혹시 오류가 발생하면 알려주세요.
꼭 풀 받고 작업해주세요!
=> [Feat] api 요청 예외처리 및 데이터 타입 수정

frontend/src/stores/scrum/useSprintStore.js, frontend/src/stores/scrum/useTaskStore.js, frontend/src/view/scrum/Task/component/TaskViewBar.vue, frontend/src/view/scrum/Task/kanban/WorkSpaceTaskKanbanPage.vue, frontend/src/view/scrum/Task/kanban/component/KanbanColumn.vue
<br>
- 칸반 보드에서 태스크를 드래그 앤 드롭할 때, 새로운 상태로 변경하는 API를 호출하여 서버에 반영되도록 구현했습니다. 이를 위해 현재 선택한 스프린트 ID를 스토어에 저장하도록 수정했습니다.
- 하위 컴포넌트에서 드래그 앤 드롭 이벤트가 발생하면 상위 컴포넌트로 이벤트를 전달하여, 태스크 리스트를 다시 불러올 수 있도록 구현했습니다.
- 드래그 대상의 상태를 파악하기 위해 item-key 속성을 상태 이름으로 설정하고, 태스크 카드의 ID를 DOM의 id 속성으로 추가하여 드래그 이벤트 시 상태와 ID를 쉽게 가져올 수 있도록 했습니다.
<br> 
드래그 했을 때, 태스크 재정렬 및 데이터 fetch 시간 때문에 깜빡임이 있습니다. 추후 수정이 필요합니다.
=> [Feat] 드래그 앤 드랍 시 상태 변경 기능 구현

frontend/src/common/component/Board/BoardList.vue, frontend/src/common/component/Board/ErrorBoardDetail.vue, frontend/src/common/component/Board/QABoardList.vue, frontend/src/stores/board/useErrorStore.js, frontend/src/view/board/component/DateComment.vue, frontend/src/view/board/detail/ErrorDetailPage.vue
<br>
- 에러 상세 페이지 조회 시 발생하던 문제들을 수정했습니다.
- router 설정에서 라우트 이름이 index.js와 일치하지 않아, 이름을 맞추고 누락된 파라미터를 추가했습니다.
- ErrorBoardDetail.vue 컴포넌트에서 사용된 키 값들이 API 명세서와 달라 데이터를 정상적으로 불러오지 못하는 문제를 해결했습니다.
- 기존에 QaStore의 메서드를 호출하도록 되어 있던 부분을 ErrorBoard 메서드로 수정하여, 올바른 스토어의 데이터를 참조하도록 변경했습니다.
- 코드 일관성을 유지하기 위해 ErrorBoard 스토어를 Composition API 방식으로 리팩토링했습니다.
- 데이터를 불러오는 동안 로딩 상태를 표시하도록 수정했습니다. 데이터가 오기 전에 loading 메시지를 띄우고, 데이터를 가져온 후에 실제 내용을 렌더링하도록 구현했습니다.
<br>
=> [Fix] 에러 상세 조회 수정

backend/api-server/src/main/java/minionz/apiserver/common/responses/BaseResponseStatus.java, backend/api-server/src/main/java/minionz/apiserver/scrum/task/TaskController.java
<br>
- 워크스페이스 드래그 앤 드랍을 할 때는 해당 스프린트에 참여했는 지에 대한 권한으로 확인합니다. 그러나 마이 스페이스는 이미 권한을 확인하여 반환한 태스크에 대한 것들이기 때문에 권한을 스프린트로 확인하지 않도록 추가 구현했습니다.
<br>
=> [Feat] 나의 태스크 상태 변경 구현
